### ISSUE TITLE
Resource entry limit in Internet Explorer 10

### ISSUE THREAD

**Issue by dhineshbabu** [w3c/resource-timing#104]
Hi,

We are trying to capture the wep page resources through resource timing API in Internet Explorer 10. We are able to see only 500 resources entries after that the values are not getting updates. I am running the below command from IE10 developer tools console. 
window.performance.getEntriesByType('resource')

Any setting I can tune in developer tools or in IE10 to increase the limit?

Thanks,
Dhinesh

**Comment by JosephPecoraro** [comment]
You may be able to increase the size using the [`setResourceTimingBufferSize`](https://w3c.github.io/resource-timing/#dom-performance-setresourcetimingbuffersize) API to increase the size. Note that this will have a slight memory cost as the PerformanceEntry objects will stay around for the lifetime of the page unless you clear them with `clearResourceTimings`.

Or you can use the [`PerformanceObserver`](https://w3c.github.io/performance-timeline/#the-performanceobserver-interface) API, and observe "resource" entries as they are created. In this case you won't need to care about the buffer size, you will just always receive an update when there are new entries.

**Comment by nolanlawson** [comment]
AFAIK we don't support `setResourceTimingBufferSize()` (it's a no-op). Do you have a web page to reproduce so we can compare results across browsers?

**Comment by skjindal93** [comment]
@dhineshbabu You can [setResourceTimingBufferSize](https://w3c.github.io/resource-timing/#dom-performance-setresourcetimingbuffersize) API to increase the buffer size. But, in IE, in order to do that, you will first have to clear the resource timing buffer.

`window.performance.clearResourceTimings();
window.performance.setResourceTimingBufferSize(<size>)`

**Comment by toddreifsteck** [comment]
Thanks, @skjindal93 !! Closing this issue.
