### ISSUE TITLE
Add workerStart attribute to measure (Service)Worker startup time

### ISSUE THREAD

**Issue by igrigorik** [w3c/resource-timing#11]
If the app is ServiceWorker-enabled then all fetches are routed to the SW, where they may be fulfilled from local cache, rewritten, forwarded to remote server, etc. However, the SW script may be terminated at any point and may need to be (re)started prior to servicing the request - e.g. navigation request spools up a worker, which is then killed, and a new worker is started up to service a subresource fetch. 

**The application needs to be able to distinguish and measure the worker startup time.** 

---

Attribute definition:

> **workerStart**: The workerStart attribute must return a DOMHighResTimeStamp [HR-TIME] with the time immediately before the user agent starts the Worker required to service the request. If the worker process is already available, then this attribute must return the same value as fetchStart.

For [processing section](http://w3c.github.io/resource-timing/#processing-model) update (add new step before 3.5): 

> If the current browsing context has a registered Service Worker, immediately before a user agent starts the worker process or forwards the request to an existing worker process, record the current time as workerStart.

Does that look reasonable? Anything I'm forgetting? `</handwaving>`

_P.S. Once we iron out the language here, we'll need to make a similar update to Navigation Timing.._

/cc @jakearchibald @slightlyoff @KenjiBaheux

**Comment by slightlyoff** [comment]
Love it.

**Comment by toddreifsteck** [comment]
This seems reasonable. Adding @aliams to thread.

**Comment by vigneshshanmugam** [comment]
This is awesome :+1:

**Comment by yoavweiss** [comment]
Sounds great!

What would that value be set to when SW is not installed? identical to fetchStart? Zero? Or should it simply not be there?

**Comment by hiroshik850223** [comment]
+1

**Comment by igrigorik** [comment]
> What would that value be set to when SW is not installed? identical to fetchStart? Zero? Or should it simply not be there?

To be consistent with how other attributes are initialized (e.g. secureConnectionStart), initializing to zero when SW is not present seems like the best way to go. This way you also have a clear indicator of whether SW is used or not.

**Comment by KenjiBaheux** [comment]
This will be quite useful, thanks for working it out.

**Comment by KenjiBaheux** [comment]
Filed https://code.google.com/p/chromium/issues/detail?id=465640 to track in blink
