### ISSUE TITLE
InitiatorType of service worker navigation preload

### ISSUE THREAD

**Issue by horo-t** [w3c/resource-timing#110]
I'm trying to expose the timing information of service worker navigation preload responses.
https://crbug.com/712809

According to the current spec, the initiatorType of the PerformanceResourceTiming of the preload responses must be "other".
But I think it is more convenient if we can use "navigationpreload" or something like it.

**Comment by igrigorik** [comment]
Still trying to wrap my head around implications of "navigation preload", but on first pass.. shouldn't the initiator be "navigation". From what I understand, the navigation proceeds in parallel with the worker startup, so initiator shouldn't change..

**Comment by yoavweiss** [comment]
Related Chromium change (including tests): https://chromium-review.googlesource.com/c/chromium/src/+/941342

**Comment by yoavweiss** [comment]
I tried to add a note, but it seemed out of place, and something that really belonged in Fetch. Looking at Fetch, the "navigation" destination seems to just fall off the definition and a note seemed spurious.

With the tests in place to make sure implementations won't get it wrong in the future, I now feel a note is not really necessary.

Closing, but feel free to reopen if you disagree.
