### ISSUE TITLE
ResourceTiming entry for the main (i.e. Initial) page/request

### ISSUE THREAD

**Issue by mvadu** [w3c/resource-timing#111]
I am confused and wated to get clarification on what is the expected behavior as per w3c to report ResourceTiming details for the main i.e. initial page. For example, if you navigate to https://www-eng-x.llnl.gov/documents/tests/txt.html it has 1.7KB of text, and refers only one 569 byte long gif image.
![image](https://cloud.githubusercontent.com/assets/8618235/26386270/a68dec0c-4013-11e7-82bf-f10938a0ebbb.png)

But `window.performance.getEntriesByType("resource")` shows only one entry for the image. What does the spec asks browsers to expose resource details ( I mean size information, `transferSize`, `encodedSize` etc) for the main page?
 
```JavaScript
window.performance.getEntriesByType("resource")
	[PerformanceResourceTiming]0: 
		PerformanceResourceTimingconnectEnd: 943.1050000000001
		connectStart: 628.02
		decodedBodySize: 264
		domainLookupEnd: 628.02
		domainLookupStart: 609.695
		duration: 596.1400000000001
		encodedBodySize: 264
		entryType: "resource"
		fetchStart: 596.7650000000001
		initiatorType: "img"
		name: "https://www-eng-x.llnl.gov/bitmaps/up.gif"
		redirectEnd: 0
		redirectStart: 0
		requestStart: 943.3100000000001
		responseEnd: 1192.9050000000002
		responseStart: 1191.525
		secureConnectionStart: 806.6300000000001
		startTime: 596.7650000000001
		transferSize: 569
		workerStart: 0
```

**Comment by igrigorik** [comment]
Yep, that's correct behavior. To get stats about the main document use Navigation Timing -- i.e. `performance.getEntriesByType("navigation")`.

**Comment by mvadu** [comment]
@igrigorik thank you sir.. One small followup clarification.. How `PerformanceNavigationTiming` returned from `window.performance.getEntriesByType("navigation")` is different from `PerformanceTiming` returned from `window.performance.timing` ? looking at the members `PerformanceNavigationTiming` seems to be an extension of `PerformanceTiming` with extra details. 
So the recommendations is to use `performance.getEntriesByType("navigation")` going forward instead of `performance.timing`?

```
PerformanceTiming 
	connectEnd 
	connectStart 
	domComplete 
	domContentLoadedEventEnd 
	domContentLoadedEventStart 
	domInteractive 
	domLoading 
	domainLookupEnd 
	domainLookupStart 
	fetchStart 
	loadEventEnd 
	loadEventStart 
	navigationStart 
	redirectEnd 
	redirectStart 
	requestStart 
	responseEnd 
	responseStart 
	secureConnectionStart 
	unloadEventEnd 
	unloadEventStart 
```
```
PerformanceNavigationTiming
	connectEnd
	connectStart
	decodedBodySize
	domComplete
	domContentLoadedEventEnd
	domContentLoadedEventStart
	domInteractive
	domainLookupEnd
	domainLookupStart
	duration
	encodedBodySize
	entryType
	fetchStart
	initiatorType
	loadEventEnd
	loadEventStart
	name
	redirectCount
	redirectEnd
	redirectStart
	requestStart
	responseEnd
	responseStart
	secureConnectionStart
	startTime
	transferSize
	type
	unloadEventEnd
	unloadEventStart
	workerStart
```

**Comment by igrigorik** [comment]
@mvadu take a look at the "status of this document" section: https://w3c.github.io/navigation-timing/ - it highlights the key differences between NT1 and NT2.. You should be using NT2. :-)

**Comment by mvadu** [comment]
@igrigorik thank you again!! NT2 it is..!
