### ISSUE TITLE
Existing Test gap:  Verify that toJSON is created properly

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/resource-timing#115]
The WebIDL test verifies the existence of the method, but we've seen that sometimes properties are not serialized properly historically. We need a test for this.

**Comment by igrigorik** [comment]
In https://github.com/w3c/web-platform-tests/pull/6428#issuecomment-314257196 @tobie indicated that this should already be implemented.. @tobie can you confirm?

**Comment by toddreifsteck** [comment]
It isn't possible for the WebIDL test to do this. It has no way to construct the object and exercise the method.

**Comment by toddreifsteck** [comment]
Unless, of course, the objects ARE constructable.. which ours currently aren't. Sorry for the run-on comments...

**Comment by tobie** [comment]
Idlharness tests the following for `[Default]` toJSON:

1. That there is a toJSON method.
2. It's length, etc. 
3. That it returns an object.
4. That each expected attribute is present on the returned object. 
5. That each attribute of the returned object has the correct type (or has a toJSON method).

**Comment by toddreifsteck** [comment]
Yes.. So it is asking type information but it is not validating the members. That requires the object to be constructed.

On Jul 11, 2017, at 11:44 PM, Tobie Langel <notifications@github.com<mailto:notifications@github.com>> wrote:


Idlharness tests the following for [Default] toJSON:

  1.  That there is a toJSON method.
  2.  It's length, etc.
  3.  That it returns an object.
  4.  That each expected attribute is present on the returned object.
  5.  That each attribute of the returned object has the correct type (or has a toJSON method).

**Comment by tobie** [comment]
I'm not sure what you mean by validating the members.

**Comment by plehegar** [comment]
This should be addressed in https://github.com/w3c/web-platform-tests/pull/7488
Note that the idlharness rejects unknown serialized attribute, such as serverTiming. @tobie, I don't think it should otherwise this is going to be a tracking nightmare.

**Comment by tobie** [comment]
> Note that the idlharness rejects unknown serialized attribute, such as serverTiming. @tobie, I don't think it should otherwise this is going to be a tracking nightmare.

Mind filing an issue? idlharness is in the wpt repo, now.

**Comment by plehegar** [comment]
@tobie , see https://github.com/w3c/web-platform-tests/issues/7491

**Comment by igrigorik** [comment]
@plehegar ditto: https://github.com/w3c/navigation-timing/issues/74#issuecomment-333640896

**Comment by plehegar** [comment]
Fixed in https://github.com/w3c/web-platform-tests/pull/7477
See http://w3c-test.org/navigation-timing/idlharness.html

**Comment by igrigorik** [comment]
👍
