### ISSUE TITLE
domainLookupStart and domainLookupEnd during HTTP/2 Connection Reuse

### ISSUE THREAD

**Issue by sajal** [w3c/resource-timing#116]
For `domainLookupStart` and `domainLookupEnd` the spec says:-

    The same value as fetchStart, if a persistent connection [RFC7230] is used or the resource is retrieved from relevant application caches or local resources.

How does this apply to HTTP/2 Connection Reuse [RFC 7540 section 9.1.1] , where a DNS lookup is required prior to the browser being able to issue the request?

**Comment by igrigorik** [comment]
Nothing special for HTTP/2 here. If a new h2 connection is required, then it'll capture that time in specified timestamps. Otherwise, its a persistent connection and above logic applies.

**Comment by sajal** [comment]
I think the spec should make the http2 reuse behaviour clear.

**Comment by igrigorik** [comment]
There is nothing specific to http2 here, a persistent connection is a persistent connection -- H1 connections can be reused as well. Closing, as there is nothing spec actionable here.
