### ISSUE TITLE
How do dns and connectStart handle multiple ip/name options?

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/resource-timing#123]
If a networking subsystem found multiple name/IP addresses when doing DNS resolution, it may attempt
1. DNS lookup A returns 1 IP and 1 name address
2. Tcp connection to the IP Address is attempted and fails
3. DNS lookup B on name address returns IP address
4. Tcp connection to IP Address B completes

Do we record connectStart before step 2 or before step 4?

**Comment by toddreifsteck** [comment]
Options:
a. domainLookupEnd could occur after connectStart
b. we reset domainLookupStart at step 3

@igrigorik will send email to figure out what Chrome does. Will try to lock at TPAC.

**Comment by igrigorik** [comment]
@toddreifsteck reviewing this once more, what's the second lookup querying for here? Presumably, first lookup can receive multiple IPs, and we then iterate through those. In which case, domainLookupEnd finishes and connectStart begins, potentially with retries under the hood..

Relevant Chromium bits:
- https://cs.chromium.org/chromium/src/net/base/load_timing_info.h?sq=package:chromium&l=70
- https://cs.chromium.org/chromium/src/chrome/browser/net/load_timing_browsertest.cc

**Comment by toddreifsteck** [comment]
We need to update the processing model to have the wording for resetting connectStart that already exists in retrieving connectStart.

This will allow a gap between domainLookupEnd and connectStart.

**Comment by yoavweiss** [comment]
Removing the "needs tests" label, as I'm not sure this is at all testable.

@toddreifsteck Are there specific clients that behave that way and that will retry DNS if the connection fails in hope of getting another response?

**Comment by yoavweiss** [comment]
> We need to update the processing model to have the wording for resetting connectStart that already exists in retrieving connectStart.
> 
> This will allow a gap between domainLookupEnd and connectStart.

@toddreifsteck It's not clear to me what's the spec gap here is. Looking at step 14 of the [processing model](https://w3c.github.io/resource-timing/#processing-model):
"record the time as connectStart immediately before initiating the connection to the server and record the time as connectEnd immediately after the connection to the server or the proxy is established. A user agent may need multiple retries before this time."

In my reading, the retry case is covered. Is the language not clear enough? Would you like it changed to something like:
"record the time as connectStart immediately before initiating the **latest successful** connection to the server and record the time as connectEnd immediately after the **latest successful** connection to the server or the proxy is established. A user agent may need multiple retries before this time."? Would that be clearer?
