### ISSUE TITLE
Unusual RT timings in IE & Edge

### ISSUE THREAD

**Issue by fshort** [w3c/resource-timing#129]
Hi,
I'm seeing an unusual scenario with some XHR resource timing captures in IE11 and Edge where the only timing populated is the startTime (sample below). All other timing fields are 0 values. I read through the RT spec and couldn't find a valid scenario where this would occur. Is this defined behavior and if so, could someone describe which scenario(s) this can happen? The domain for the page and the XHR are the same so I don't believe this is CORS related.

Thanks,
Fred

`
{
    "name":"https://myorg.com/restservice/test",
    "entryType":"resource",
    "startTime":995.896,
    "duration":0,
    "initiatorType":"xmlhttprequest",
    "redirectStart":0,
    "redirectEnd":0,
    "fetchStart":0,
    "domainLookupStart":0,
    "domainLookupEnd":0,
    "connectStart":0,
    "connectEnd":0,
    "secureConnectionStart":0,
    "requestStart":0,
    "responseStart":0,
    "responseEnd":0
  }
`

**Comment by plehegar** [comment]
I read the spec as follows: fetchStart have to return startTime at the minimum.

responseStart, and responseEnd seems to indicate the same unless there was a failure.

connectStart, domainLookupStart, domainLookupEnd, secureConnectionStart, requestStart have to return the same value as fetchStart unless there was a failure.


. Others may return 0 if the resource is in the cache.

**Comment by toddreifsteck** [comment]
@fshort , the location to report an IE/Edge bug is https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

Please include a repro that one of the Edge developers can review when you open the bug and add a link here.

**Comment by fshort** [comment]
Thanks for the help. Closing this issue for now.

**Comment by fshort** [comment]
**Update**: this turned out to be a timing issue. Evidently, IE will create an partial entry in the ResourceTimings array initially comprised of the data above. As the XHR goes through its lifecycle, the additional timings are updated. My process was picking up the array entries while some were still in this incomplete state.

Have others observed this behavior and is this in alignment with the spec or should I file a bug with Microsoft? I couldn't find anything in the spec that specifically refers to how browsers should create entries. FWIW, Chrome and Firefox don't behave this way based on my testing.

**Comment by nicjansma** [comment]
@fshort Based on the [processing model](https://www.w3.org/TR/resource-timing-2/#processing-model), ResourceTiming entries should be "complete" before they make it to the ResourceTiming buffer in the PerformanceTimeline (Step 21).

We are considering changing this for some scenarios (it would actually be useful to get notified of just-starting resources via some sort of PerformanceObserver so you can know about all outstanding fetches), but I believe this specific issue is an IE bug.

**Comment by fshort** [comment]
opened bug with Microsoft here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16739941/
