### ISSUE TITLE
initiatorType test cases

### ISSUE THREAD

**Issue by nicjansma** [w3c/resource-timing#138]
Followup from https://github.com/w3c/resource-timing/issues/132

Let's build test cases for all initiator types.

**Comment by annevk** [comment]
See also #142. It's rather problematic that this feature isn't build on top of existing infrastructure.

**Comment by yoavweiss** [comment]
> See also #142. It's rather problematic that this feature isn't build on top of existing infrastructure.

Agreed (even though, this feature preceded said infrastructure).
We can try to deprecate parts of it, as web compatibility permits. The long run plan is to replace it with initiator info that is more informative, and will probably build on top of `Request.destination` as much as possible.

**Comment by annevk** [comment]
"Fetch" existed before 2011 though, see https://www.w3.org/TR/2009/WD-html5-20090825/infrastructure.html#fetching-resources for instance.

**Comment by yoavweiss** [comment]
This seems to be largely covered by https://wpt.fyi/resource-timing/resource_initiator_types.html.
The test passes on Chromium, and other engines has several failures. We should file bugs against them.

@nicjansma - Can you take a look at the test and see if there are some initiator types it's not properly covering?

**Comment by yoavweiss** [comment]
Thanks for the tests, @nicjansma. Closing!

**Comment by yoavweiss** [comment]
I think the initiatorType tests we recently landed got some of the values wrong. I fixed it up at https://chromium-review.googlesource.com/c/chromium/src/+/1040925

@nicjansma Can you please review the tests there to see that we agree on the new values before landing?
