### ISSUE TITLE
secureConnectionStart should account for non-HTTPS secure transports

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/resource-timing#14]
See http://www.stevesouders.com/blog/2014/08/21/resource-timing-practical-tips/

**Comment by toddreifsteck** [comment]
Discussed on call. Closing.

**Comment by hiroshik850223** [comment]
Hi, I agree that secureConnectionStart returns undefined, when we don't use HTTPS. Why is this issue close?

**Comment by plehegar** [comment]
Because we agreed it needs to return 0 instead.
