### ISSUE TITLE
setResourceTimingBufferSize should not clear "resource timing buffer full flag" when the buffer has shrunk

### ISSUE THREAD

**Issue by rniwa** [w3c/resource-timing#145]
When `setResourceTimingBufferSize` is called to shrink the resource timing buffer size, it's inappropriate to clear "resource timing buffer full flag" since that would result in every new queuing of a resource timing performance entry to fire resourcetimingbufferfull event even though there was no space made available in the buffer in the last firing of the event.

**Comment by npm1** [comment]
Should setResourceTimingBufferSize fire a resourcetimingbufferfull event if the maxSize parameter is less than or equal to resource timing buffer current size? I see that Chrome currently fires resourcetimingbufferfull in this case (regardless of the flag) but that is not stated anywhere in the spec.

**Comment by npm1** [comment]
I checked that Firefox 58 does not fire the event in this case, and the spec does not prompt this, so I think I should just fix the Chrome behavior.

**Comment by igrigorik** [comment]
Resolved via https://github.com/w3c/resource-timing/pull/146.
