### ISSUE TITLE
`origin-or-null` definition and TAO processing

### ISSUE THREAD

**Issue by yoavweiss** [w3c/resource-timing#152]
I'm failing to find if and where `origin-or-null` is defined. The "null" case is also not addressed in the "timing allow check" processing model.

IIUC, we need to:
* Add a definition for `origin-or-null`. I'm not sure if the `origin` part should be a token or there are more specific syntax definitions at https://tools.ietf.org/html/rfc7230#appendix-B or elsewhere (CCing @reschke for his opinion)
* Point the origin comparison in the processing model to https://tools.ietf.org/html/rfc6454#section-5 as https://tools.ietf.org/html/rfc6454#section-4 doesn't really return a string.
* Add tests that make sure that origin comparison in TAO also works for non-standard ports, doesn't work for different schemes, etc.
* Add a `null` related condition in the processing model.

Thoughts?

**Comment by igrigorik** [comment]
`origin-or-null` is defined in Fetch: https://fetch.spec.whatwg.org/#origin-header

**Comment by yoavweiss** [comment]
OK, cool. So we can just link to that definition. The rest of the points still stand.

**Comment by yoavweiss** [comment]
Following a [discussion on IRC](https://freenode.logbot.info/whatwg/20181012#c1763402) with @annevk, I tend to think this will require larger Fetch integration than I initially thought:
* "null" handling should work for tainted or opaque origins
* In order to support that, we're better off relying on some version of [Fetch's serializing a request origin](https://fetch.spec.whatwg.org/#serializing-a-request-origin), only we'll need an equivalent using the Document's origin. I'm not quite sure how that would work.
* We'd need tests for all of the above.

**Comment by annevk** [comment]
It seems that a number of these things you can and should address today, either by fixing or adding issue markers, so implementers don't implement security vulnerabilities.

**Comment by yoavweiss** [comment]
> You'd invoke https://html.spec.whatwg.org/#ascii-serialisation-of-an-origin directly on document's origin (which is defined at https://dom.spec.whatwg.org/#concept-document-origin by the way).

OK, so that's one missing piece that would cover opaque origins and is fairly easy to add.



> The main problem I see with your current setup is that you have no notion of redirects so if A requests B which redirects to A, this would consider it same-origin, despite it leaking information about B. That seems bad.

Good point. AFAICT, fixing it would require a) RT to start using Fetch's Response objects rather than "resource" b) Fetch to propagate the "tainted" flag from Request to Response. I can definitely add an issue marker in the short term, but fixing it seems like it would fit well with the larger Fetch-based "rebase".

**Comment by annevk** [comment]
Thanks. Calling these issues out inline would already be a huge help, especially since not everyone has time to study the issue list in detail.

**Comment by yoavweiss** [comment]
@annevk Seems like the cross-origin redirect sandwich case is already covered by a [WPT](https://wpt.fyi/results/resource-timing/resource_timing_cross_origin_redirect_chain.html?label=stable&aligned=true).

**Comment by annevk** [comment]
As far as I can tell `resource-timing/resource_timing_cross_origin_redirect_chain.html` doesn't test same-origin to cross-origin, but I'm not really familiar with the harness in use there.

**Comment by toddreifsteck** [comment]
@yoavweiss Could you explain why fetch integration is 100% required? Can't we simply add a bit of verbage to monkey patch this in to RT 2? I may simply be naive. :-)

**Comment by toddreifsteck** [comment]
Pulling it back so we can discuss. Sorry if that causes any hassle. This one feels like it belongs in 2 from my sniff of it.

**Comment by marcoscaceres** [comment]
Generally speaking, if you can avoid monkey patching that's preferred - as when implementing, it means implementers can safely send things into the fetch machinery, which can be updated independently of this spec. The monkey patch risks getting out of date with the spec it is patching, meaning that a middle layer could end up being required for compat with this spec.

**Comment by yoavweiss** [comment]
https://github.com/w3c/resource-timing/pull/172 addresses some of the definitions here that don't require Fetch integration, and adds a note regarding the security concerns. A review of that as well as https://github.com/web-platform-tests/wpt/pull/13518 would be appreciated. A previous [comment](https://github.com/w3c/resource-timing/issues/152#issuecomment-429350696) covers the missing bits in Fetch and related to Fetch integration. Monkey-patching those here don't seem like a small feat, nor does that seem helpful to do outside the context of the wider Fetch integration.

So with that, I'll create a new issue that makes sure the above PRs land for L2, but bump this one back to L3, for the larger scope Fetch integration.
