### ISSUE TITLE
Section 5.1 Processing Model supporting text change from 'underlined' to 'in parenthesis'

### ISSUE THREAD

**Issue by zaphodtx** [w3c/resource-timing#154]
In the 2nd sentence of the first paragraph of section 5.1, change the wording to match the current Figure 1.  I.e. change "Attributes underlined" to "Attributes in parenthesis".

Version: [W3C Editor's Draft 19 April 2018](https://w3c.github.io/resource-timing/)

**Comment by nicjansma** [comment]
Thanks!  https://github.com/w3c/resource-timing/pull/156
