### ISSUE TITLE
Make secureConnectionStart a mandatory attribute

### ISSUE THREAD

**Issue by igrigorik** [w3c/resource-timing#16]
Given the push towards [securing the web](http://www.w3.org/2001/tag/doc/web-https) and growing adoption of HTTP/2 (which requires HTTPS in many UAs), I'd like to propose that we make this a mandatory attribute both in resource and navigation timing.

**Comment by igrigorik** [comment]
@plehegar @toddreifsteck I recall an earlier discussion mentioning that "optional attributes" are a bad idea. Any objections to removing the optional language for this one?

**Comment by toddreifsteck** [comment]
No objection from me. Let’s remove the optional tag.

**Comment by plehegar** [comment]
Full support from me to remove the optional tag

**Comment by toddreifsteck** [comment]
Full support from me as well

**Comment by yoavweiss** [comment]
Full support from me as well!

**Comment by toddreifsteck** [comment]
Merged
