### ISSUE TITLE
DNS lookups can occur even when reusing a connection

### ISSUE THREAD

**Issue by npm1** [w3c/resource-timing#160]
The spec currently says that domainLookupStart must return "The same value as fetchStart, if a persistent connection [RFC7230] is used or the resource is retrieved from relevant application caches or local resources." Similar for domainLookupEnd. However, there could be a DNS lookup even when reusing a connection, so the spec currently allows (domainLookupEnd - domainLookupStart) to be 0 in some cases where a DNS lookup actually occurs. This feels wrong.

More context: see Chromium [bug](https://crbug.com/760059).

**Comment by jasonslyvia** [comment]
I have some RUM data that proves `dnsLookupStart` earlier than `fetchStart`, don't know if it fits into this case

<img width="468" alt="dns_lookup_start_before_fetch_start" src="https://user-images.githubusercontent.com/1336484/45741643-b3715f00-bc2a-11e8-82aa-4d3c02f5115f.png">

**Comment by rniwa** [comment]
Filed https://github.com/whatwg/fetch/issues/810 in the fetch spec.

**Comment by yoavweiss** [comment]
I agree that this needs to be better defined so that the DNS value matches reality in those cases.
