### ISSUE TITLE
Should 404 codes be considered aborts?

### ISSUE THREAD

**Issue by npm1** [w3c/resource-timing#165]
I'd like some clarification regarding whether ResourceTiming should consider this to be an abort or not. This is important due to the spec's current language saying that the user agent may or may not report entries for fetches that were initiated but then aborted. On a related note, it feels like we should just agree on a more strict specification: either aborts should be reported by all user agents or they should not be reported by any user agent.

**Comment by igrigorik** [comment]
What's the motivation for treating 404 as an abort? It's a valid and successful server response that should be surfaced to the application — e.g. an API request for a non-existent resource.

**Comment by npm1** [comment]
That sounds reasonable to me. But then I think the spec needs to be clearer. Currently, we have "Resources for which the fetch was initiated, but was later aborted (e.g. due to a network error) MAY be included as PerformanceResourceTiming objects in the Performance Timeline and MUST contain initialized attribute values for processed substeps of the processing model."

So there's a couple of options here but either way this needs a spec change:

- Keep aborts optional. In this case, there is a difference in how RT handles aborts vs non-aborts. This means we need to properly define what an abort is in this context. Then an implementor can identify that 404 is an error code that does not correspond to an abort and needs to be reported always.
- Make aborts mandatory. This means removing the "MAY" keyword from the spec, so implementors can understand that all aborts should be reported as well. In this case we wouldn't need to define what an abort is since all cases must be reported.

**Comment by igrigorik** [comment]
For context, past related discussion(s): https://github.com/w3c/resource-timing/issues/12

The tl;dr is that the current wording is (unfortunately) intentionally vague due to differences in implementations, and our goal is to address this in L3. See the linked discussions and PR's in above thread for the related PR's and reverts where we pushed this to L3.

I propose we merge this into https://github.com/w3c/resource-timing/issues/39?

**Comment by npm1** [comment]
I'd suggest we keep it separate to ensure it gets addressed when integrating with Fetch. As discussed in the call, it makes sense to consider this a L3 issue.

**Comment by mikesalvia** [comment]
According to a newer discussion, this will be changed in future specs.

https://github.com/w3c/resource-timing/issues/165
https://bugs.chromium.org/p/chromium/issues/detail?id=883400&can=4&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by yoavweiss** [comment]
Just landed a [Chromium change](https://chromium-review.googlesource.com/c/chromium/src/+/1796544) to expose resource entries regardless of status code

**Comment by yoavweiss** [comment]
Seems like this was [fixed](https://bugs.webkit.org/show_bug.cgi?id=202040) for WebKit as well. Closing.
