### ISSUE TITLE
Broken links in https://w3c.github.io/resource-timing/#sec-performanceresourcetiming

### ISSUE THREAD

**Issue by miketaylr** [w3c/resource-timing#167]
I didn't check them all, but there are a few hyperlinks that just take you to https://www.w3.org/ in Section 4.3

Performance Timeline -> https://www.w3.org/#performance-timeline
PerformanceEntry -> https://www.w3.org/#the-performanceentry-interface (link also broken in the IDL)

**Comment by yoavweiss** [comment]
Thanks for reporting! This was since fixed by @marcoscaceres on https://github.com/w3c/resource-timing/pull/170
