### ISSUE TITLE
What value should secureConnectionStart have when using preexisting connection?

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/resource-timing#17]
Probably the same language as connectionStart.

**Comment by igrigorik** [comment]
"When a secure transport is used, this attribute must return the time immediately before the user agent starts the handshake process to secure the current connection. If a persistent connection [RFC7230] is used or the resource is retrieved from relevant application caches or local resources, this attribute must return value of domainLookupEnd. If a secure transport is not used, this attribute must return zero."

Does that look right? @toddreifsteck can you land this, or should I make the update?

**Comment by toddreifsteck** [comment]
Resolved by #34
