### ISSUE TITLE
Clarify cross-origin resources

### ISSUE THREAD

**Issue by alanwaketan** [w3c/resource-timing#173]
When the spec refers cross-origin resources, are we talking about response or request origin?
For example, in resource_timing_cross_origin_redirect_chain.html, the resource loaded in frameContext was requested from a cross-origin site but then the respond is from the same-origin site. Should we treat the resource as cross-origin or same-origin? The test itself suggests the former. However, I didn't see any spec language defining this.

**Comment by alanwaketan** [comment]
Thanks Anne for clarification. Let's say if multiple redirects happen, what origins are required in TAO? Also do we need TAO for each intermediate response?

Let's say:
A.com -> B.com -> C.com
1. C.com has TAO B.com, B.com has TAO A.com, is this the only case that goes through?
2. Or as long as C.com has TAO A.com, it will go through?

**Comment by alanwaketan** [comment]
May I ask why resource_TAO_cross_origin_redirect_chain.html would pass? The last redirect doesn't have TAO. Can you clarify where the TAO needs to be present in the chain?

**Comment by annevk** [comment]
If multiple redirects happen, the origin gets tainted and will be send out as "null". C should see "null" and reply accordingly. It shouldn't see B.com. And yes, each response in the chain needs to have TAO, unless there are some same-origin responses and it hasn't gone cross-origin yet.

(The tests may well be incorrect.)

**Comment by alanwaketan** [comment]
Thanks Anne for response. I am so sorry that it takes me a while to response.

I would like to write a few examples and see if I understand you correctly. All examples assume the main frame is on A.com, and the redirect chain in each example assumes an iframe within the main frame.

Example 1:
A.com => B.com (TAO) => A.com (TAO) => A.com (TAO)
The main frame should see the iframe's timing.

Example 2:
A.com => A.com => B.com (TAO) => A.com (TAO)
The main frame should see the iframe's timing.

Example 3:
A.com => B.com (TAO) => A.com (TAO) => A.com
The main frame should not see the iframe's timing.

Example 4:
A.com => B.com => A.com (TAO)
The main frame should not see the iframe's timing.

Example 5:
A.com => B.com => A.com
The main frame should not see the iframe's timing.

**Comment by alanwaketan** [comment]
Thanks Anne for the clarification and sorry for late response.

I would like to give examples to see if I fully understand everything. Let's say we have a main frame in A.com, and some redirections happen within its child frame. How could the main frame get accesses to the child frame's timing information in each example?

Example 1.
B.com (TAO) => A.com (TAO) => A.com (TAO)
Yes.

Example 2.
B.com (TAO) => A.com (TAO) => A.com
No.

Example 3.
A.com => A.com => B.com (TAO) => A.com (TAO)
Yes.

Example 4.
B.com => C.com (TAO)
No.

Example 5.
B.com => A.com
No.

**Comment by yoavweiss** [comment]
Similarly to https://github.com/w3c/resource-timing/issues/152#issuecomment-429350696, we'd need to use Fetch Response objects for this and need Fetch Response objects to contain that information. Monkey patching this doesn't seem like the right way to go, outside the context of a larger rebase on top of Fetch.

**Comment by yoavweiss** [comment]
Happy to add the above example to the spec, as well as make sure the tests in https://github.com/web-platform-tests/wpt/pull/13518 cover all those scenarios and make that an L2 blocker. The wider scope definition is something that will happen in #152 as part of L3.

**Comment by yoavweiss** [comment]
Closed by #196. It did not add explicit examples but the (handwavy) language there should make the above clearer.

**Comment by yoavweiss** [comment]
#196 didn't really close this one. https://github.com/w3c/resource-timing/pull/197 will

**Comment by yoavweiss** [comment]
On the last call, we decided to postpone this alignment to L3, as it most probably requires implementation changes.

**Comment by yoavweiss** [comment]
Closing as #197 was merged
