### ISSUE TITLE
Resource timing vs Resource timing lvl 2

### ISSUE THREAD

**Issue by shacharz** [w3c/resource-timing#2]
Hi,

I wasn't sure about the whether these are 2 different specs, and what is the state of their drafting.
It's said in the spec of resource timing that: 
"The audio and video elements are specifically covered in the Resource Timing Level 2 specification and not in this version of the specification." (http://www.w3.org/TR/resource-timing/#introduction-1).
Resource-timing 2 looks like copy&paste of an old version of resource-timing. (http://w3c.github.io/resource-timing/).

Thanks in advance

**Comment by igrigorik** [comment]
Should be addressed in latest revision. Closing.
