### ISSUE TITLE
Be a bit more explicit about which subresources are to be ignored from stylesheets

### ISSUE THREAD

**Issue by npm1** [w3c/resource-timing#200]
The spec currently says "If the resource is fetched by a cross-origin stylesheet which was fetched with no-cors policy, abort the remaining steps." This seems to mean that all subresources from such stylesheet should be ignored. But the current wording could be interpreted as only direct fetches from the stylesheet. For example, consider this fetch chain:
stylesheet A -> stylesheet B -> resource C
In this case, when A is no-cors cross-origin, I believe C's RT information should not be exposed, and we should make this clear.

**Comment by yoavweiss** [comment]
Concluded on the call: even if B and C are same-origin, they should not be exposed

**Comment by toddreifsteck** [comment]
Per W3C call on 8/1, we need to add tests and spec language to ensure browsers are able to implement properly.

**Comment by yoavweiss** [comment]
I just spent some time thinking of a language that would allow us to hand wavily define this without saying "dependency trees" which are a big and loaded term...

Ideas welcome! :)

**Comment by yoavweiss** [comment]
/cc @annevk @noamr 

Anne - I'd appreciate ideas on how we can know in Fetch that a resource was fetched by no-cors CSS

@jakearchibald @wanderview - Thoughts? Did y'all define this for SWs?

**Comment by mfalken** [comment]
This is still tracked here https://github.com/w3c/ServiceWorker/issues/719 for SW and we haven't defined it.

**Comment by annevk** [comment]
Cross-origin no-cors CSS, right? CSS could set request's service-workers mode to "none" for such requests. I suppose it could also set request's timing allow failed flag and things would work out, but we might want to make it a bit clearer that's a flag a user of fetch could set as currently it's described as an internal detail.

**Comment by yoavweiss** [comment]
> Cross-origin no-cors CSS, right?

Indeed!



> I suppose it could also set request's timing allow failed flag

I don't think that's sufficient, as we want those URLs to not be reported at all, while TAO would just reduce the information they expose.
Sounds like we need a separate flag for "this was fetched by a cross-origin no-cors CSS", which CSS should then set. Does that make sense?

**Comment by yoavweiss** [comment]
If we had such a flag, that's something that we could include, and avoid queueing an entry in those cases. 
A "triggered from CSS" is also something that would've been useful for the current [`initiatorType` definition](https://www.w3.org/TR/resource-timing-2/#dom-performanceresourcetiming-initiatortype) (where BG images and fonts report "css"), although that's something I'd love to deprecate and remove at some point, and replace with actual initiator info..

**Comment by noamr** [comment]
Researching this now, I'm seeing that in the [CSS import](https://drafts.csswg.org/css-cascade-5/#import-processing) spec, it says that "The origin of an imported style sheet is the origin of the style sheet that imported it.". That sounds in itself a bit like a cross-origin violation, and I wonder how we should handle the case where:

Document -> CSS-1(same origin) -> Import CSS-2 (cross-origin no-cors) -> Resource (same origin as CSS-2)

According to the language in the aforementioned import rule spec, the styles are maybe the same origin but the resource is a different origin?

Note that unlike an image for example, an imported style is never truly opaque if it's imported inside a same-origin stylesheet, as its contents are 100% visible to CSSOM (the imported stylesheet doesn't change CSSOM's [origin-clean flag](https://drafts.csswg.org/cssom/#concept-css-style-sheet-origin-clean-flag). 

Besides the note above, I think dealing with the initial use-case brought here, where the original stylesheet from `link` is cross-origin no-cors (not "origin-clean") would be quite straightforward in the HTML/CSS spec, and would probably not require any changes to fetch. But I wanted to clarify the note first.

**Comment by noamr** [comment]
... to read a 

> Researching this now, I'm seeing that in the [CSS import](https://drafts.csswg.org/css-cascade-5/#import-processing) spec, it says that "The origin of an imported style sheet is the origin of the style sheet that imported it.". That sounds in itself a bit like a cross-origin violation, and I wonder how we should handle the case where:
> 
> Document -> CSS-1(same origin) -> Import CSS-2 (cross-origin no-cors) -> Resource (same origin as CSS-2)
> 
> According to the language in the aforementioned import rule spec, the styles are maybe the same origin but the resource is a different origin?
> 
> Note that unlike an image for example, an imported style is never truly opaque if it's imported inside a same-origin stylesheet, as its contents are 100% visible to CSSOM (the imported stylesheet doesn't change CSSOM's [origin-clean flag](https://drafts.csswg.org/cssom/#concept-css-style-sheet-origin-clean-flag).
> 
> Besides the note above, I think dealing with the initial use-case brought here, where the original stylesheet from `link` is cross-origin no-cors (not "origin-clean") would be quite straightforward in the HTML/CSS spec, and would probably not require any changes to fetch. But I wanted to clarify the note first.

Note that the implementations actually create an opaque "CSSImportRule" which makes the language in the spec a bit ambiguous - CSSOM doesn't act like a CSS import rule is same origin when it's not.

**Comment by noamr** [comment]
Note: Currently [CSS @import processing](https://drafts.csswg.org/css-cascade-5/#import-processing) is defined only in prose. I believe it needs to be define in terms of fetch or refer back to the HTML `link` processing before resource-timing issues can be addressed.

**Comment by noamr** [comment]
Depends on https://github.com/w3c/csswg-drafts/issues/562

**Comment by noamr** [comment]
Should be fixed by https://github.com/w3c/csswg-drafts/pull/6715

**Comment by noamr** [comment]
Closing now that https://github.com/w3c/csswg-drafts/pull/6715 is merged.
