### ISSUE TITLE
Specify TAO check for 304 responses

### ISSUE THREAD

**Issue by npm1** [w3c/resource-timing#201]
In these responses, the TAO header to be used must be the one from the original resource. Maybe it is worth clarifying this on the spec since it may require implementors to store these (Chrome has a special field for it). Also, make sure there is sufficient test coverage for these cases.

**Comment by rniwa** [comment]
@annevk what does CORS do here?

**Comment by annevk** [comment]
The CORS check is applied after we obtain a response for a 304 from the cache. So I'm not sure I agree with OP that this is the way to go.

This is yet another symptom of this specification not being defined from first principles.

**Comment by yoavweiss** [comment]
> The CORS check is applied after we obtain a response for a 304 from the cache. So I'm not sure I agree with OP that this is the way to go.

Yeah, but it's not clear (to me at least) what happens in cases where e.g. both the 304 response and the previously cached 200 response contain `Access-Control-Allow-Origin` with non-identical values. The relevant [section](https://tools.ietf.org/html/rfc7234#section-4.3.4) in RFC 7234 doesn't seem to define that explicitly.

> This is yet another symptom of this specification not being defined from first principles.

Care to elaborate on that?

**Comment by annevk** [comment]
From that RFC:

> use other header fields provided in the 304 (Not Modified) response to replace all instances of the corresponding header fields in the stored response.

> Care to elaborate on that?

The root cause of this issue is this header's validation not being defined in (terms of) Fetch.

**Comment by yoavweiss** [comment]
> use other header fields provided in the 304 (Not Modified) response to replace all instances of the corresponding header fields in the stored response.

OK, cool. Agree that it makes sense for TAO to do the same. From discussion on the last WG call, I'm not sure @npm1 would disagree.

**Comment by npm1** [comment]
Just to be clear, what we'd like the behavior to be is that the 304 completely ignores the TAO header from the original resource?

I'm ok with that behavior. Can we add a test to see what implementations are doing right now? This could be a breaking change, but it's worth aligning more with what other specs are specifying.

**Comment by yoavweiss** [comment]
If I'm reading the bit that @annevk cited from the HTTP RFC correctly, we want TAO headers from the 304 to override the cached headers only if they exist. Otherwise, when the 304 includes no TAO headers, the ones from the cached response should be used.

**Comment by npm1** [comment]
Ah ok, I think that would be better.
