### ISSUE TITLE
Add tests for not-same-site nested contexts

### ISSUE THREAD

**Issue by yoavweiss** [w3c/resource-timing#204]
As requested by @bzbarsky on https://github.com/web-platform-tests/wpt/pull/13823/files#r265195654

**Comment by yoavweiss** [comment]
@tommckee1 - Do you think this would be something you can tackle as part of your work on the nested context tests?

**Comment by tommckee1** [comment]
Makes sense to me!

I've filed crbug.com/1294845 to track/link to the larger refactoring effort.

**Comment by noamr** [comment]
Added tests: https://github.com/web-platform-tests/wpt/pull/33581
