### ISSUE TITLE
Clarify that TAO needs to be set even on same origin resource after cross-origin redirects

### ISSUE THREAD

**Issue by rniwa** [w3c/resource-timing#207]
In order to match CORS, we should make sure TAO is set in the header after cross origin redirects.

**Comment by yoavweiss** [comment]
On yesterday's call it was decided that we should aim this for L2

**Comment by toddreifsteck** [comment]
@yoavweiss has multiple active test PRs to understand the open issues. We will also need spec updates to address this issue.
