### ISSUE TITLE
PerformanceResourceTimings never published, nondeterministically

### ISSUE THREAD

**Issue by bmk5cc** [w3c/resource-timing#227]
Not sure if this would be the place to open up this issue (perhaps it would go to individual browsers), but it seems like all browsers on iOS have a bug where the PerformanceResourceTimings never get published for a particular request, nondeterministically. This doesn't occur on Android. Also occurs on safari on desktop. Images below are from safari (had to block out some private info).

<img width="1399" alt="Screen Shot 2020-03-30 at 4 03 16 PM" src="https://user-images.githubusercontent.com/26190138/77971716-47060000-72a4-11ea-9079-7cba0c63145d.png">
In the image above, on the last line, we see the network request for 
75cf70-fb77-8d5b-fbc4-25bfad86dba1-2

Note the -2

<img width="1411" alt="Screen Shot 2020-03-30 at 4 35 30 PM" src="https://user-images.githubusercontent.com/26190138/77971803-83d1f700-72a4-11ea-9bef-f6a657bb2380.png">
We also see the performance timings for the -2 request in the network tab.

<img width="1387" alt="Screen Shot 2020-03-30 at 4 02 56 PM" src="https://user-images.githubusercontent.com/26190138/77971727-4c634a80-72a4-11ea-8b5f-dc0b57017dfd.png">
Yet the performance timings are missing from `performance.getEntries()` which I output in the console (the blacked out stuff is the same between the console output and network tab). I have a loop running every second, checking if the timing exists, but even after over an hour it never appears. We can see in the timings array, the -1 appears, yet the -2 never appears. I have requests going from -0, -1, to -2.

This happens nondeterministically.

**Comment by rniwa** [comment]
All browsers on iOS use WebKit as the browser engine. Please report bugs on bugs.webkit.org.

This repository is to track the standards discussions of PerformanceResourceTimings, not bugs in particular implementations.
