### ISSUE TITLE
Timing-Allow-Origin may expose allowed URLs

### ISSUE THREAD

**Issue by noamr** [w3c/resource-timing#228]
A doubt re `Timing-Allow-Origin`, maybe just needs  a clarification.

I'm thinking of a situation where `Timing-Allow-Origin` is set to a particular URL or URL list.
Since TAO doesn't require sending the `Origin` header like CORS, the server might not know the origin the request is coming from, and therefore it will have to send all the allowed origins in the response.

Wouldn't this create a possible scenario where a client could sniff other embedder URLs of a resource by reading that response?

CORP handles this by a more coarse syntax like `same-site` / `same-origin`. Maybe that would be a safer alternative, especially if we move to something like `Metadata-Allow-Origin`(see https://lists.w3.org/Archives/Public/public-webappsec/2020Jul/0005.html)

**Comment by noamr** [comment]
@npm1 @yoavweiss ?

**Comment by npm1** [comment]
Hmm yea I think that's right, generally the response TAO value would be the same. Note that having `same-origin` does not save much, as in TAO you specify a full origin (not URL). Also, I thought resource response headers are not exposed by default to the client?

On other note, we were hoping to align TAO more with CORS, but now that there's CORP I'm not sure which of those it's best to align with.

**Comment by yoavweiss** [comment]
The resource response headers are indeed not exposed to JS, but are exposed to the client itself (so, e.g. a crawler could access this resource and be exposed to this data).
In practice, I'm not aware of resources that include a lot of TAO origins (it would only be an issue if the embedder's ReferrerPolicy blocks sending the origin with the request). An HTTPArchive crawl could tell us if I'm wrong.

**Comment by noamr** [comment]
> In practice, I'm not aware of resources that include a lot of TAO origins (it would only be an issue if the embedder's ReferrerPolicy blocks sending the origin with the request). An HTTPArchive crawl could tell us if I'm wrong.

 I think it's a chicken and egg thing... The current API will make it so that TAO would mainly be useful with `*` as a value, otherwise it may expose embedder URLs to crawlers (unlike CORS which requires the client to send an `Origin`).

I'm raising this because of the recent conversation about metadata (https://github.com/w3c/csswg-drafts/issues/5165).
I'm thinking that maybe `Timing-Allow-Origin` should fold into `CORP` together with exposing EXIF resolution in srcset (https://github.com/whatwg/html/pull/5574#issuecomment-654100058), and that `CORP` should be defined along the lines of "This is an openly available resource, we're allowing any embedder to use it".

**Comment by yoavweiss** [comment]
As [discussed](https://docs.google.com/document/d/1fHD8Eqyt6vInbZu3vkIVhPVrRPtGpNmaQgzKppVW4xY/edit#heading=h.srgapc6ov14s) on last week's call, we can add a note in the spirit of “If you don't have an Origin nor Referrer headers, then don't send TAO unless it's `*`”.

The broader "CORP vs. CORS" subject is probably something we want to discuss at TPAC, hopefully as a cross-WG discussion with WebAppSec folks.

**Comment by noamr** [comment]
Closing for now, feel free to reopen.
