### ISSUE TITLE
[Question] What happens when the resource timing entries buffer is full?

### ISSUE THREAD

**Issue by Nithanaroy** [w3c/resource-timing#230]
Is there a recommendation for browsers on how to clear the resource timing entries buffer when it is full? On Chrome and Safari (latest), I see they just drop the new entries when it is full. Wouldn't a circular buffer be more useful?

**Comment by npm1** [comment]
You can call clearResourceTimings() and/or setResourceTimingBufferSize(). Having a circular buffer would still make you lose the earlier entries unless you already read them.

**Comment by Nithanaroy** [comment]
Yeah, thank you.
But does the spec define anything about dealing with situation when buffer is full? Is it safe to assume that all major browsers (tracked by caniuse for example), throw away events once the buffer is full like Chrome and Safari (latest)?

**Comment by yoavweiss** [comment]
The spec define that entries that exceed the buffer, broadly speaking:
* Get added to a secondary buffer
* Fire the [`resourcetimingbufferfull`](https://w3c.github.io/resource-timing/#dfn-resourcetimingbufferfull) event
* If the handler increased the buffer size, the secondary buffers gets copied over

The full processing model is defined [here](https://w3c.github.io/resource-timing/#dfn-add-a-performanceresourcetiming-entry)

Closing, but feel free to reopen if that doesn't answer your question.
