### ISSUE TITLE
requestStart definition differ with navtimg

### ISSUE THREAD

**Issue by plehegar** [w3c/resource-timing#25]
In navtimg, we have:
[[
responseEnd of type DOMHighResTimeStamp, readonly
    This attribute MUST return a DOMHighResTimeStamp with a time value equal to the time immediately after the user agent receives the last byte of the current document or immediately before the transport connection is closed, whichever comes first. The document here can be received either from the server, relevant application caches or from local resources.
]]

In RT, we have:
[[
responseEnd of type DOMHighResTimeStamp, readonly
    This attribute MUST return the time immediately after the user agent finishes receiving the last byte of the resource from relevant application caches or from local resources.
]]

I presume the navtiming is more accurate (it also matches the responseStart definition).

**Comment by igrigorik** [comment]
@plehegar I'm confused by this one.. The bug says requestStart differs but your snips show responseEnd. Which one is the issue? requestStart looks good to me, and it does seem that we should update responseEnd in RT.

**Comment by toddreifsteck** [comment]
Agree that resource timing responseEnd resource timing should be updated.

**Comment by igrigorik** [comment]
I believe #32 should resolve this issue.

**Comment by plehegar** [comment]
LGTM. Thanks.
