### ISSUE TITLE
4.5.1 "timing allow check" should be called from somewhere and get "the resource" as input

### ISSUE THREAD

**Issue by yoavweiss** [w3c/resource-timing#251]
The check is already integrated with Fetch as it operates on a Response object (and most of the related processing is in Fetch). However, the input to that algorithm could be clarified.

**Comment by noamr** [comment]
I don't exactly understand what's missing. Prose about how TAO should work? Seems like that exists.

**Comment by yoavweiss** [comment]
I believe that previously, "timing allow check" was defined in Fetch but not properly called from the Resource Timing processing model. That is no longer the case, so we can close this.
