### ISSUE TITLE
WPT Cleanup

### ISSUE THREAD

**Issue by tommckee1** [w3c/resource-timing#254]
As noted on the Jan 21 Web Perf Working Group call, we've noticed there are some parts of the spec that aren't being covered by Web Platform Tests. Right now, the tests are quite dissimilar and inconsistent which makes it more difficult to see what is and isn't covered.

This issue will track cleanup efforts to normalize and update the tests to a more tenable state. Specifically, we want to
- Prefer `promise_test` to `async_test`
- Prefer `fetch_tests_from_window` to hand-rolled message passing
- Apply a consistent naming scheme to the files

**Comment by tommckee1** [comment]
Chrome tracking bug: crbug.com/1171767

**Comment by noamr** [comment]
@yoavweiss I think we can close this.
