### ISSUE TITLE
Which DNS timings should be exposed when fetching redirected resource

### ISSUE THREAD

**Issue by tommckee1** [w3c/resource-timing#258]
On https://www.w3.org/TR/resource-timing-2/#dom-performanceresourcetiming-domainlookupstart (and for domainLookupEnd) if there are redirects (same-origin or otherwise) there can be multiple DNS queries.

Which query/queries end up populating the domainLookupStart and domainLookupEnd?

**Comment by tommckee1** [comment]
@yoavweiss thoughts?

**Comment by yoavweiss** [comment]
The last request in the redirect chain. The [processing model](https://www.w3.org/TR/resource-timing-2/#processing-model) overrides the value in step 12, which runs for each request in the redirect chain.

**Comment by tommckee1** [comment]
That makes sense... thanks!

**Comment by npm1** [comment]
It's true that the 'getter' is not entirely clear about this, and perhaps it should. That said, Noam is going to probably get rid of all of this so not sure if we wanna clear it up at this point.
