### ISSUE TITLE
Current definition of `startTime` exposes total redirect time even when TAO fails

### ISSUE THREAD

**Issue by noamr** [w3c/resource-timing#260]
Since `startTime` points to `fetchStart`, the caller can mark the time before calling `fetch` to a cross-origin resource, and figure out the redirect time as the difference between that time and `startTime`.

Proposing that `startTime`would be `min(redirectTime, startTime)`, same as in the TAO case, obfuscating the detailed timing of redirects.

**Comment by npm1** [comment]
Do we also need to gate `fetchStart` on TAO then? Or should `fetchStart` just be the initial fetch start time, instead of the final one, when no TAO?

**Comment by noamr** [comment]
> Do we also need to gate `fetchStart` on TAO then? Or should `fetchStart` just be the initial fetch start time, instead of the final one, when no TAO?

Yes, it needs to be the initial one IMO.

I think though that a clean and easy to understand implementation of TAO would be that TAO-protected responses would only have `startTime` and `duration` and nothing else.

**Comment by npm1** [comment]
If we gate on TAO it does not need to be the initial one though. Perhaps it may be better to keep the semantics and just restrict it as needed, since it's an old feature.

`responseEnd` could also be available in non-TAO, I guess, since that's just the end time of `duration`.

**Comment by noamr** [comment]
> If we gate on TAO it does not need to be the initial one though. Perhaps it may be better to keep the semantics and just restrict it as needed, since it's an old feature.

Yes, I meant in the TAO-fail secenario.

> `responseEnd` could also be available in non-TAO, I guess, since that's just the end time of `duration`.

Sure, doesn't hurt :)

**Comment by annevk** [comment]
Due to https://github.com/w3c/resource-timing/pull/261 adopting the work of https://github.com/whatwg/fetch/pull/1185 it'll end up fixing this.

**Comment by npm1** [comment]
We may want to add tests for whatever was the behavior change to ensure implementors can follow along.

**Comment by annevk** [comment]
To be clear, in the event of non-TAO Resource Timing will get a fetch timing info struct where everything is 0, except for the members that map to startTime and fetchTime, which will be identical and correspond to startTime, and for the member that maps to responseEnd, which will be responseEnd.

**Comment by noamr** [comment]
This is now fixed in the FETCH spec and covered with tests. Closing, please reopen if needed.
