### ISSUE TITLE
Add tests for TAO-fail behavior changes since FETCH integration

### ISSUE THREAD

**Issue by noamr** [w3c/resource-timing#264]
After FETCH integration, the entries would include only the following when TAO fails:

- startTime (which is the lower between redirectStart / redirectStart)
- responseEnd
 duration (responseEnd - startTime)

The rest of the attributes are zeroed. See https://github.com/w3c/resource-timing/issues/260 for reasoning.

The tests need to reflect the new behavior.

**Comment by npm1** [comment]
Also implementations need to change presumably... @rniwa @bdekoz @sefeng211 for heads up.

**Comment by noamr** [comment]
See https://github.com/web-platform-tests/wpt/pull/28563
