### ISSUE TITLE
No mention to WebIDL in conformance section

### ISSUE THREAD

**Issue by himorin** [w3c/resource-timing#275]
A text to mention WebIDL for IDL fragments in conformance section has been deleted in this update: https://github.com/w3c/resource-timing/pull/170/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L184

Is this a desired update?

**Comment by npm1** [comment]
Not sure @marcoscaceres @yoavweiss

**Comment by marcoscaceres** [comment]
No, definitely don't want that stuff. It adds no value. It would be good if we could eliminate it in all specs.

**Comment by nicjansma** [comment]
Closing per @marcoscaceres's comments

**Comment by yoavweiss** [comment]
[Clarification](https://lists.w3.org/Archives/Public/public-web-perf/2021Jun/0009.html) from Marcos:
> Just to be clear, the redundant text is/was: 
> """
> The IDL fragments in this specification must be interpreted as
> required for conforming IDL fragments, as described in the [[WEBIDL]] 
> specification.
> """
> The above is like saying, "phrases written in the English language MUST be interpreted as [[English]]". It's tautological and redundant.
