### ISSUE TITLE
Definition of initiatorType removed

### ISSUE THREAD

**Issue by MasonM** [w3c/resource-timing#276]
https://github.com/w3c/resource-timing/pull/80 added clarification for the `initiatorType` attribute, which I found very useful while tracking down an obscure Chrome bug. That text was subsequently removed in https://github.com/w3c/resource-timing/pull/261 and is no longer present at https://w3c.github.io/resource-timing/. The latter PR talks about moving things to [the fetch spec](https://fetch.spec.whatwg.org/), but that spec doesn't have the text either. Where should I go to find the definition and possible values for `initiatorType`?

**Comment by yoavweiss** [comment]
It might be worthwhile to bring that text back as a note. It doesn't really belong in Fetch, as it's Fetch callers that determine the initiator type.

@noamr - FYI

**Comment by noamr** [comment]
> It might be worthwhile to bring that text back as a note. It doesn't really belong in Fetch, as it's Fetch callers that determine the initiator type.
> 
> @noamr - FYI

Yes, I support bringing it back as a note.
