### ISSUE TITLE
Duplicate definitions

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/resource-timing#279]
The spec has the following duplicate definitions (`data-lt="step-final-queue"` x3!), which I'm not entirely sure how to fix. 

@noamr, could you clarify what it's trying to do there? 

Additional ProTip: definitions shouldn't include links to other specs. Also, there doesn't seem to be any reason to use `data-cite=` there, specially for any specs under our control. 

```
            <li>
              <dfn data-lt="step-final-queue"><a data-cite=
              "PERFORMANCE-TIMELINE-2#dfn-queue-a-performanceentry">Queue</a>
              |entry|.</dfn>
            </li>
            <li>
              <dfn data-lt="step-final-queue"><a data-lt=
              'add a PerformanceResourceTiming entry'>Add</a> |entry| to
              |global|'s <a data-cite=
              "PERFORMANCE-TIMELINE-2#dfn-performance-entry-buffer">performance
              entry buffer</a>.</dfn>
            </li>
          </ol>
          <p>
            <dfn data-lt="step-final-queue">To <dfn data-export="">setup the
            resource timing entry</dfn> for <a>PerformanceResourceTiming</a>
            |entry| given DOMString |initiatorType|, DOMString |requestedURL|,
            [=/fetch timing info=] |timingInfo|, and a DOMString |cacheMode|,
            perform the following steps:</dfn>
          </p>
```

**Comment by noamr** [comment]
Regarding the duplicate refs: probably a copy/paste error we missed in review. The `data-cite`s were there before I think (I don't remember the whole thing).

**Comment by marcoscaceres** [comment]
@noamr, ok no problem. I'm still a bit unsure how to fix it though? Any chance you could help me with a PR? Happy to review.

**Comment by noamr** [comment]
> @noamr, ok no problem. I'm still a bit unsure how to fix it though? Any chance you could help me with a PR? Happy to review.

I'm not sure what they were doing there in the first place, I think you can just remove them in your tidy PR... @yoavweiss ?

**Comment by marcoscaceres** [comment]
heh, ok it's not just me then 😅 I couldn't make heads of tails of it either. I'll update the PR now... @yoavweiss, let us know!

**Comment by yoavweiss** [comment]
Just LGTMed the PR. Removing them SGTM

**Comment by marcoscaceres** [comment]
Closed via https://github.com/w3c/resource-timing/pull/278
