### ISSUE TITLE
PerformanceObserver when ResourceTiming array is full

### ISSUE THREAD

**Issue by nicjansma** [w3c/resource-timing#28]
I can't remember if this has been discussed already.

I know that PerformanceTimeline2 and PerformanceObserver are still being spec'd out (http://www.w3.org/TR/2015/WD-performance-timeline-2-20150716/), but I would like to ensure that once ResourceTiming events get wired into PerformanceObserver, RT still fires PO events even if the "legacy" ResourceTiming buffer is full.

The legacy buffer was capped (e.g. at 150 entries) to ensure an app would not have an growing buffer of RT data even if no one was listening.

But when someone is listening via a PerformanceObserver, we know that someone cares for the data, and should be able to safely deliver those RT entries to the listener even if the regular RT array is full.

**Comment by igrigorik** [comment]
> I would like to ensure that once ResourceTiming events get wired into PerformanceObserver, RT still fires PO events even if the "legacy" ResourceTiming buffer is full.

Yes, that's the plan. FWIW, I'd suggest we move this discussion into: https://github.com/w3c/performance-timeline/issues/13. We'll spec the PO processing model there.

**Comment by igrigorik** [comment]
This is resolved in https://github.com/w3c/performance-timeline/pull/46 - observer notifications are independent of the currently defined buffers.
