### ISSUE TITLE
Running tidy locally results in churn

### ISSUE THREAD

**Issue by yoavweiss** [w3c/resource-timing#282]
I tried to run tidy locally after my latest PR, but it resulted in a lot of unrelated changes.
Running tidy effectively means that pending PRs have to be merged back manually, so ideally, we'd have a way to run it in a consistent way as part of CI (so that tidy changes only apply to new prose and not to existing one).

/cc @marcoscaceres @caribouW3 @nicjansma

**Comment by marcoscaceres** [comment]
Happy to set that up, but we need to do one "big tidy" and then we should be good to run it on CI.

**Comment by yoavweiss** [comment]
Yeah, that makes sense. I think we ran one already, so pending PRs would already need a manual rebase. In other words, now is as good a time as any :)

**Comment by marcoscaceres** [comment]
We did indeed! Cool.
