### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by mnot** [w3c/resource-timing#289]
`Timing-Allow-Origin` is defined using ABNF as:

> Timing-Allow-Origin = 1#( origin-or-null / wildcard )

However, neither the `origin-or-null` nor the `wildcard` rules are defined in the document, or referenced elsewhere.

**Comment by yoavweiss** [comment]
Thanks for reporting! :)

For `origin-or-null`, we should refer to https://fetch.spec.whatwg.org/#origin-header
For `wildcard`, we should refer to https://fetch.spec.whatwg.org/#http-new-header-syntax
