### ISSUE TITLE
Should favicon loading times be exposed to the document?

### ISSUE THREAD

**Issue by noamr** [w3c/resource-timing#299]

**Comment by noamr** [comment]
Favicon links do not trigger a link "onload", but they do trigger a resource timing entry when accessed.
Are favicons a "resource", or some general hint to the browser? Does this expose any privacy issues, maybe "visited" type information?

**Comment by noamr** [comment]
I checked the webkit implementation, it does indeed have some special handling of favicons, but mostly after the icon is loaded. The icon is fetched in the normal way, and also FETCH mentions favicons as having an "image" destination in terms of CSP.

So maybe it's ok to keep this behavior, but decide on the initiator type (should be `link` I believe), and add a WPT that shows that favicons don't expose visited info.

**Comment by yoavweiss** [comment]
Keeping the behavior (and properly specifying/testing it, with a `link` initiator type) SGTM
