### ISSUE TITLE
Consider to limit the max size of resource timing buffer

### ISSUE THREAD

**Issue by smaug----** [w3c/resource-timing#304]
Somewhat recently a major social media web site used size 100000 for the buffer. That caused significant jank in the browsers.
Implementations are a bit different, so methods to query the data have different performance characteristics.
I had some old tests for this
https://bug1688312.bmoattachments.org/attachment.cgi?id=9198744 is for getEntriesByName
https://bug1688312.bmoattachments.org/attachment.cgi?id=9198778 is for getEntriesByType

getEntriesByName is very fast in Blink, getEntriesByType is very slow (which is why the getEntriesByType test does only 100 iterations).
Both methods are ok-ish in Gecko. (I didn't have Webkit to test this).

Not only does the effectively endless buffer cause performance issues, but it does also lead to higher memory usage.
And seemingly setResourceTimingBufferSize is rather error prone API when even the largest websites have issues caused by it.

**Comment by npm1** [comment]
Ping - should we move this issue to User Timing?

**Comment by smaug----** [comment]
I'm not sure in which spec this should be handled. setResourceTimingBufferSize is defined in resource timing spec, which is why I filed this here.

**Comment by npm1** [comment]
The title implies this is about resource timing indeed, but the demos are about user timing, so the request is a bit unclear.

**Comment by npm1** [comment]
Reading this again, perhaps the request is to have a max threshold so that `setResourceTimingBufferSize` cannot have a crazy large size? I would argue that this is not necessary: if the developer sets this size, then they should understand that it comes at a price. Also, an entry is only created for resource fetches, so it should be very uncommon for such extremely large numbers to be reached in the first place. The issue of the performance of the methods is perhaps a separate issue which should be addressed by each user agent separately. OK to close this?

**Comment by smaug----** [comment]
The APIs are very error prone. When sites like Facebook make these mistakes (and they even have a performance team, AFAIK), it hints that something should be done to the APIs.

**Comment by npm1** [comment]
What maximum size would you suggest then?

**Comment by nicjansma** [comment]
I believe this was the original bug, which is for a site that had a very large ResourceTiming buffer size that ended up filling up and causing performance issues: https://bugzilla.mozilla.org/show_bug.cgi?id=1686930

**Comment by yoavweiss** [comment]
If you're interested, I'm more than happy to introduce spec flexibility to impose an implementation defined limit. Let me know.

**Comment by noamr** [comment]
Closing based on previous comments. Feel free to reopen if want to pursue this.
