### ISSUE TITLE
Clarify RT entry creation when iframe changes `src`

### ISSUE THREAD

**Issue by noamr** [w3c/resource-timing#316]
Take the following scenario:
- Load an iframe with a `src`
- When the iframe loads, the owner document changes the `src` to a different URL.

In WebKit/Chromium, there would be 1 resource entry in the performance timeline. In Gecko there would be 2.
The previous Resource Timing spec was a bit vague about it, where the scenario presented there was about internal iframe navigations.

I believe that WebKit/Chromium try to follow the spirit of the old spec, but that Gecko is doing the actual right thing (there's no point in hiding the resource entry for a resource loaded explicitly by the owner document).

This affects the iframe bit of https://github.com/whatwg/html/issues/6542.

**Comment by noamr** [comment]
See WPT: https://github.com/web-platform-tests/wpt/pull/32490/files#diff-cd501c053b40769b623223a45356d4b2468dcbdc326a6c5c5c17758d1f832b6eR26

The second test succeeds in Firefox and fails in Chrome/Safari.

**Comment by yoavweiss** [comment]
That makes sense. It's possible that Chromium's implementation of the restriction was over-zealous...

/cc @achristensen07

**Comment by achristensen07** [comment]
Acknowledged.  I don't have a strong preference either way

**Comment by yoavweiss** [comment]
@noamr - can you file a crbug on this?

**Comment by noamr** [comment]
> @noamr - can you file a crbug on this?

I was going to once I file the HTML PR, as right now this is unspecified. But I can start with a crbug.

**Comment by noamr** [comment]
> @noamr - can you file a crbug on this?

Done. https://bugs.chromium.org/p/chromium/issues/detail?id=1290721
and webkit https://bugs.webkit.org/show_bug.cgi?id=235561

together with the spec PR https://github.com/whatwg/html/pull/7531/files

**Comment by noamr** [comment]
https://github.com/whatwg/html/pull/7531 and the new WPTS clear this up.
