### ISSUE TITLE
Drop the "L2" part from the published version

### ISSUE THREAD

**Issue by yoavweiss** [w3c/resource-timing#326]
Currently [published version](https://www.w3.org/TR/resource-timing-2/) has "L2" in its title and URL. We should drop this, as we decided on a living standard model.

/cc @caribouW3 @nicjansma

**Comment by caribouW3** [comment]
Depends on https://github.com/w3c/transitions/issues/337

**Comment by caribouW3** [comment]
fixed in https://github.com/w3c/resource-timing/pull/359
