### ISSUE TITLE
Failed deploy

### ISSUE THREAD

**Issue by yoavweiss** [w3c/resource-timing#357]
https://github.com/w3c/resource-timing/actions/runs/3337738762/jobs/5524468581 failed with "Link href and text differ" error message.

@caribouW3 - would you be able to take a look?

**Comment by yoavweiss** [comment]
Echidna seems to have [failed](https://labs.w3.org/echidna/api/status?id=9eef4af7-c9d8-4516-a7ae-b49f73a3afbc) with an auth error..

**Comment by caribouW3** [comment]
fixed, https://www.w3.org/TR/resource-timing/ published successfully (I also merged the PR fixing the title before that)
