### ISSUE TITLE
Should the spec mention "Queue entry" at somepoint? 

### ISSUE THREAD

**Issue by sefeng211** [w3c/resource-timing#367]
I am just glancing through the spec. One thing that I am confused is that I don't see the spec says to `Queue` the entry when the entry is added to the resource timing buffer. Or rather, the spec doesn't specify when an entry should be queued to the observers. 

For instance, in the **add a PerformanceResourceTiming entry** step, shouldn't we say `queue the entry` after the `Add new entry to the performance entry buffer` sub-step? 

Another place is in the **copy secondary buffer**  step, do we need to say `Queue the entry` after the `Add entry to the end of performance entry buffer` step? 

I see the **mark resource timing** step mentions this, however it's not referenced anywhere in the spec.

**Comment by yoavweiss** [comment]
@noamr - can you take a look? Did that got lost in the refactor?

**Comment by noamr** [comment]
https://w3c.github.io/resource-timing/#dfn-mark-resource-timing 

3. Queue entry

Am I missing something?

**Comment by sefeng211** [comment]
Ah okay, I am wrong.

I think I got lost while comparing the Firefox implementation and the spec. Apparently Firefox queues the entry when we are adding it to the buffer, which doesn't align the current specification. So I thought the spec would be the same. 

Sorry about this!
