### ISSUE TITLE
Define Resource Timing in terms of Fetch

### ISSUE THREAD

**Issue by igrigorik** [w3c/resource-timing#39]
Expressing RT in terms of Fetch will force us to clarify a lot of the current edge cases:
- reporting of redirects and failed fetches (see https://github.com/w3c/resource-timing/issues/12)
- reporting of multi-request fetches (see https://github.com/w3c/resource-timing/issues/21)
- initiator reporting (see https://github.com/w3c/resource-timing/pull/36)

Some ideas on mechanics of how to accomplish this in https://github.com/w3c/resource-timing/pull/36#issuecomment-143150479. This will be a substantial effort with required changes both in RT and Fetch specs.

**Comment by plehegar** [comment]
See https://github.com/w3c/web-platform-tests/pull/2884/commits/e21f1ce62e87216960376b86c9d49ba282dd129d for test.

**Comment by noamr** [comment]
I believe this can be closed.

**Comment by yoavweiss** [comment]
Amazing work!!
