### ISSUE TITLE
Clarify what transferSize, encodedBodySize should return in various conditions

### ISSUE THREAD

**Issue by valenting** [w3c/resource-timing#40]
Since we also return resource timing entries for cached resources, it should be specified if transferSize should return the same value it had during the first load, or just an estimation (body+headers).

Secondly, since we sometimes get 4XX/5XX responses with content, it needs to be clarified how we handle this case. I assume it would still return non-zero values, even if this is not the body of the resource we requested?

Also, while usually encodedBodySize is the same as the Content-Length response header, in some cases it could differ. I assume we want the actual number of bytes on the wire.

**Comment by valenting** [comment]
Also, is it correct if the transferSize is smaller than encodedBodySize in cases where the resource is cached, but we hit the network in order to revalidate, and transferSize is the size of the headers?

**Comment by igrigorik** [comment]
Great feedback, we do need to clarify this stuff in the spec. Before I do though...

>Since we also return resource timing entries for cached resources, it should be specified if transferSize should return the same value it had during the first load, or just an estimation (body+headers).

`transferSize` should be set to 0 when response comes from cache; it's meant as an explicit signal that resource was fetched from the network.

> Secondly, since we sometimes get 4XX/5XX responses with content, it needs to be clarified how we handle this case. I assume it would still return non-zero values, even if this is not the body of the resource we requested?

Right. It should return the sum of response headers and response payload body, regardless of response code (2xx, 3xx, 4xx, 5xx, ...)

> Also, while usually encodedBodySize is the same as the Content-Length response header, in some cases it could differ. I assume we want the actual number of bytes on the wire.

Correct. Content-Length is also not guaranteed to be present.. so we want to report the actual number of bytes the client received.

> Also, is it correct if the transferSize is smaller than encodedBodySize in cases where the resource is cached, but we hit the network in order to revalidate, and transferSize is the size of the headers?

- If valid response comes from cache: `transferSize` should be set to 0, encodedBodySize should be the size of the cached payload body before any content-codings are removed.
- If a revalidation happens: `transferSize` should report the size of response headers (there is no body to account for), and encodedBodySize should be the size of the cached payload body before any content-codings are removed.

Does that make sense?

**Comment by valenting** [comment]
Yes, this sounds like a sane behaviour for the spec.
Thanks!

**Comment by igrigorik** [comment]
@valenting ptal at https://github.com/w3c/resource-timing/pull/41.

**Comment by taxi666** [comment]
Why encodedBodySize is 0 sometimes?
