### ISSUE TITLE
Distinguish "Not-Allowed" from zero value entries

### ISSUE THREAD

**Issue by yoavweiss** [w3c/resource-timing#42]
The introduction of integer values (`transferSize`, `encodedBodySize` and `decodedBodySize`) means that we can no longer use 0 as a value indicating that a 3rd-party origin did not pass the [timing-allow check](https://w3c.github.io/resource-timing/#timing-allow-check).

We need to define a way in which a developer can know if a certain 3rd party resource didn't include the appropriate headers, or was genuinely zero sized.

**Comment by igrigorik** [comment]
> The introduction of integer values (transferSize, encodedBodySize and decodedBodySize) means that we can no longer use 0 as a value indicating that a 3rd-party origin did not pass the timing-allow check.

I think this still works.. e.g. if `domainLookupStart` is zero then you known that TAO permission bits are missing, regardless of what *Size attributes report.

**Comment by igrigorik** [comment]
@yoavweiss *bump*. Can we close this?

**Comment by yoavweiss** [comment]
While I agree that developers could conclude with high probability the absence of TAO and therefore deduce what a 0 value means for `transferSize` et al, it would be significantly simpler and less hacky if we'd define that a lack of TAO results in negative `transferSize` (e.g. `-1` which seems to be a popular choice in such cases). Since these sizes are unsigned in their nature, there's little risk of confusion there.

Do you see any problems with that approach? If not, I'll be happy to PR that spec change.

**Comment by igrigorik** [comment]
Hmm, I'm not convinced: we don't do this for any other attributes, they all return zero; it seems rather hacky to overload what is, effectively, a bytesize attribute with completely different meaning. I'd consider a negative value on time or size a bug.

**Comment by yoavweiss** [comment]
OK, then maybe that's not the right approach.

Still, I think that asking devs to conclude TAO state from other values is not great dev ergonomics. Maybe we should expose TAO state directly?

**Comment by igrigorik** [comment]
Hmm, is that really necessary? I don't think introduction of {transfer,decodedBody,encodedBody}Size actually changed anything, as far as ergonomics is concerned...

The developer can inspect [responseStart](http://w3c.github.io/resource-timing/#widl-PerformanceResourceTiming-responseStart): the only time it reports `0` is when TAO opt-in is necessary and missing. You don't need to check anything else; nothing has changed in this respect.

What _is_ different now, is that if TAO opt-in is present, the developer can now check transferSize: if the value is 0, then they know that the resource was served from cache. So, if the developer wants to know if a particular resource was served from cache:

```javascript
performance.getEntriesByType('resource').forEach(r => { 
 status = ""
 if (r.responseStart == 0) { status = "Unknown, TAO opt-in is missing" }
 else { 
  if (r.transferSize == 0) { status = "Served from HTTP cache" }
  else { status = "Network request was made" }
 }
 console.log(r.name + ": " + status)
})
```

**Comment by yoavweiss** [comment]
I think we agree that exposing the TAO state explicitly won't help solving new use cases.

I argue that patterns like `var isTAOServed = !r.responseStart;` are bad ergonomics and hacky. This is not something new, but it is something we can fix.

OTOH, I don't feel *that* strongly about it, so if you disagree, feel free to close.

**Comment by igrigorik** [comment]
> I argue that patterns like var isTAOServed = !r.responseStart; are bad ergonomics and hacky. This is not something new, but it is something we can fix.

Fair enough. Personally, I don't consider this to be a big deal and I've not heard developers complain about it either. As such, I'm inclined to punt on this... That said, would love to hear @plehegar and @toddreifsteck's thoughts.

**Comment by igrigorik** [comment]
*bump* 

@plehegar @toddreifsteck any thoughts?

**Comment by igrigorik** [comment]
Discussed on the call today: closing, we can revisit in the future if there is high(er) demand for it. In the meantime, you can get this behavior via example https://github.com/w3c/resource-timing/issues/42#issuecomment-206508028.
