### ISSUE TITLE
Contribute tests for resource timing

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/resource-timing#46]

**Comment by toddreifsteck** [comment]
Todd will send to @plehegar on 11/11.

**Comment by igrigorik** [comment]
@toddreifsteck @plehegar any progress on this?

**Comment by toddreifsteck** [comment]
Thanks for the poke! I've just relayed it via email internally.

**Comment by plehegar** [comment]
https://github.com/w3c/navigation-timing/issues/39

**Comment by plehegar** [comment]
Btw, we have https://github.com/w3c/web-platform-tests/pull/402 . I should go over it first and see if it's still interesting. It doesn't seem to be deployed on w3c-test.org. I'll probably end up resending it in a new PR.

**Comment by toddreifsteck** [comment]
@plehegar , I've added our resource timing tests to https://github.com/MicrosoftEdge/web-platform-tests/tree/resource-timing-enhancements . Per discussion, could you toss me a PR of the server-side updates you made? At that point, we'll PR to w3c. Thanks!

**Comment by yoavweiss** [comment]
Slightly related: seems like Firefox is [failing](https://bugzilla.mozilla.org/show_bug.cgi?id=1272605) one of the tests in the current test suite.

**Comment by igrigorik** [comment]
For reference, test pull here: https://github.com/w3c/web-platform-tests/pull/3013.

@toddreifsteck @plehegar any blockers for merging the above and resolving this?

**Comment by toddreifsteck** [comment]
No blocker on my end. @plehegar ?

**Comment by igrigorik** [comment]
https://github.com/w3c/web-platform-tests/pull/3013 was merged, closing.
