### ISSUE TITLE
Provide a way to get current buffer size?

### ISSUE THREAD

**Issue by AFBarstow** [w3c/resource-timing#48]
I don't see a way for an app to determine/get the current buffer size. An app might want to the current size if, for example, the app gets a  resourcetimingbufferfull  event.

If there is way for an app to get this data, please let me know.

**Comment by plehegar** [comment]
It seems to me that one would know in advance how many resources are expected to get fetched from the app and set the limit appropriately. If you deploy an app that runs into the limit, you can also report that back to the server and tweak your app as needed. Or maybe this is needed for CDN cases?

**Comment by plehegar** [comment]
pinging @yoavweiss in case he encountered this limitation.

**Comment by igrigorik** [comment]
> An app might want to the current size if, for example, the app gets a resourcetimingbufferfull event.

`getEntriesByType('resource').length` gives you exactly that.

Closing, please feel free to reopen if there's more to explore here.
