### ISSUE TITLE
Confusion around allowed `Timing-Allow-Origin` values

### ISSUE THREAD

**Issue by igrigorik** [w3c/resource-timing#62]
```
Timing-Allow-Origin = "Timing-Allow-Origin" ":" origin-list-or-null | "*"
```

Definition of origin-list-or-null: https://tools.ietf.org/html/rfc6454#section-7.1

```
7.1.  Syntax

   The Origin header field has the following syntax:

   origin              = "Origin:" OWS origin-list-or-null OWS
   origin-list-or-null = %x6E %x75 %x6C %x6C / origin-list
   origin-list         = serialized-origin *( SP serialized-origin )
   serialized-origin   = scheme "://" host [ ":" port ]
                       ; <scheme>, <host>, <port> from RFC 3986
```

My read of the above ABNF is that TAO _should_ allow a space separated list of origins. However, [ACAO header](https://www.w3.org/TR/cors/#access-control-allow-origin-response-header) also has origin-list-or-null but has a comment indicating that it's a single origin only -- is this a special ACAO restriction?

Today, Chrome allows a space separated [list of origins](https://bugs.chromium.org/p/chromium/issues/detail?id=594049#c4). FF [does not](https://bugzilla.mozilla.org/show_bug.cgi?id=936814#c51). Edge.. not sure. 

@toddreifsteck how does Edge handle this?
@mnot @reschke can you sanity check this as well? Am I reading this correctly?

**Comment by reschke** [comment]
1) The definition in https://www.w3.org/TR/cors/#access-control-allow-origin-response-header is incorrect in that it doesn't allow whitespace around the value. Does anybody implement that like that?

2) A spec can add restrictions in prose; in this case though it could have used serialized-origin / null instead.

**Comment by toddreifsteck** [comment]
@igrigorik Did you already put together a server to test Chrome that I could re-use for testing Microsoft Edge?

**Comment by igrigorik** [comment]
@toddreifsteck no I have not, I'm going by discussion in crbug.com/410875. We should though!

@reschke just to confirm, the BNF in the spec **does** allow a space separated list, correct?

**Comment by toddreifsteck** [comment]
Side Note--When this is resolved, we also need to create a test for this behavior.

**Comment by reschke** [comment]
@igrigorik yup

**Comment by nolanlawson** [comment]
I put together a quick test which shows whether a browser supports the space-separated origin list or not: https://github.com/MicrosoftEdge/timing-allow-origin-test

Preliminary results show that Chrome and Edge are in agreement, but Firefox indeed does not support multiple values – instead it ignores both of them. Haven't tested Safari yet.

**Comment by igrigorik** [comment]
@nolanlawson great work, thank you! Safari hasn't implemented RT (yet) so they're out of the picture of this one.

Given the discussion on the call earlier today, I believe the Edge / Chrome behavior is correct. /cc @valenting @annevk

**Comment by valenting** [comment]
So in this case we should change section 4.5.1 step 4 to indicate the algorithm must search the list for a matching origin, instead of just a case sensitive match.
Also the note saying that in practice it is only a single origin.

**Comment by valenting** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1288288

**Comment by annevk** [comment]
origin-list-or-null is at this point legacy syntax to support redirects (we later decided that redirects would not get an origin chain but rather the string "null", the serialization of an opaque origin). It's not at all about supporting multiple origin values. Note also that the authoritative standard for CORS does not have it: https://fetch.spec.whatwg.org/. Citing w3.org/TR/cors/ and depending upon it is just irresponsible.

I think what Firefox does is vastly preferable here as it matches the model we have for CORS. If we ever wanted to allow multiple actual origin values (not a redirect sequence), we should use HTTP's comma-separated-value syntax.

**Comment by reschke** [comment]
Well, the specification for "Origin" already allows a set of origins to be serialized, so inventing a new notation for that just because you don't like the existing one doesn't sound right to me.

**Comment by annevk** [comment]
If you're talking about the RFC, 1) it's obsolete in practice 2) it had a specific purpose for such a set, abusing it for a different purpose is wrong.

**Comment by reschke** [comment]
Then please clarify what the different purposes are.

Having a whitespace separated list for one purpose and comma delimited one for another one sounds strange.

**Comment by annevk** [comment]
I already did in https://github.com/w3c/resource-timing/issues/62#issuecomment-234167844. It was specifically intended for a redirect chain.

**Comment by annevk** [comment]
And in particular, the redirect chain was expected to be listed in the `Origin` header and the server was expected to echo that value literally. You wouldn't be allowed to match against individual values.

**Comment by reschke** [comment]
The description in <https://tools.ietf.org/html/rfc6454#section-7.2> does mention redirects, but it doesn't sound as if that was the only reason to specify multiple ones:

   For example, consider a user agent that executes scripts on behalf of
   origins.  If one of those scripts causes the user agent to issue an
   HTTP request, the user agent MAY use the Origin header field to
   inform the server of the security context in which the script was
   executing when it caused the user agent to issue the request.

**Comment by annevk** [comment]
That doesn't talk about multiple origin values in the slightest (and has no corresponding processing model either, not even sure what that would say).

**Comment by reschke** [comment]
Sorry, wrong paragraph. Here we go:

 In some cases, a number of origins contribute to causing the user
   agents to issue an HTTP request.  In those cases, the user agent MAY
   list all the origins in the Origin header field.  For example, if the
   HTTP request was initially issued by one origin but then later
   redirected by another origin, the user agent MAY inform the server
   that two origins were involved in causing the user agent to issue the
   request.

**Comment by annevk** [comment]
Yeah, redirects. If you go back and look at the discussion that's the only reason. And the semantics of that are completely different from granting several origins the right to expose something. That was never part of the deal.

**Comment by reschke** [comment]
Again: the spec already mentions cases other than redirects...

**Comment by annevk** [comment]
It doesn't? Please point to the processing model.

**Comment by igrigorik** [comment]
I'm missing some history here, so apologies upfront if I'm rehashing points. Re-reading the spec(s):

- Fetch no longer relies on rfc6454. It defines own ABNF for Origin and ACAO headers:
 - https://fetch.spec.whatwg.org/#origin-header: defines `origin-or-null`
 - https://fetch.spec.whatwg.org/#http-new-header-syntax: ACAO uses `origin-or-null / wildcard`
- Resource Timing, on the other hand, uses the `origin-list-or-null` definition from rfc6454. 
 - Chrome and Edge implemented `origin-list-or-null / wildcard`. 
 - Firefox implemented `origin-or-null / wildcard`.

Stating the obvious: we want to converge on consistent behavior across browsers.

In terms of use cases, `origin-or-null / wildcard` means that for any non-trivial deployment that does not want to whitelist all origins (wildcard), but wants to enable limited access to 1+ origins, the TAO header has to be dynamic which can be very challenging. For example, if I have a CDN on which I keep my static resources and multiple origins (a.foo.com, b.foo.com) from which I want to access it, I either have to have my CDN dynamically reflect a set of whitelisted origins, or I use `*`. 

Based on past experience, dynamic headers are often a problem in practice.. So, really, we're encouraging `*` or not at all. This doesn't seem right? What are the arguments against allow origin-list for TAO if we already allow `*`?

**Comment by annevk** [comment]
The argument is that we want CORS and TAO to match. If we want CORS to have sets of origins, we would use the multiple value syntax from HTTP. The space-separated syntax is tainted.

**Comment by igrigorik** [comment]
Is there an explainer, or past threads, that I can read up on that motivate why CORS doesn't allow a list of origins? I agree that consistency between CORS and TAO _would_ be nice, but it's not clear to me that this has to be the case.

**Comment by annevk** [comment]
Maybe on public-webapps or public-appformats? As I said, we might want to allow multiple origins, but not using this syntax.

**Comment by yoavweiss** [comment]
If we want to change current behavior, it's probably a good idea to start collecting usage data, as the current shipping behavior in Chromium & Edge is to allow multiple origins using that syntax.

**Comment by annevk** [comment]
Yeah, that would be good. As far as I can tell Firefox has not hit a compatibility issue thus far.

**Comment by yoavweiss** [comment]
https://codereview.chromium.org/2178973002/

**Comment by igrigorik** [comment]
Chrome telemetry:

- TAO with `*`: [~0.15% of pages](https://www.chromestatus.com/metrics/feature/timeline/popularity/1483)
- TAO with multiple origins: [~0.005% of pages](https://www.chromestatus.com/metrics/feature/timeline/popularity/1482)
- TAO with single origin: [0.017% of pages](https://www.chromestatus.com/metrics/feature/timeline/popularity/1481)

What are the next steps here?

**Comment by yoavweiss** [comment]
I guess that means that we could modify the syntax for multiple origins, if this is what we want.

**Comment by toddreifsteck** [comment]
Discussed with Yoav/Ilya. Ilya is going to update Nolan's test to test multiple headers and comma-separated header.

**Comment by igrigorik** [comment]
```diff
diff --git a/server.js b/server.js
index 75cf2e6..2e2ef7b 100644
--- a/server.js
+++ b/server.js
@@ -5,12 +5,12 @@ var fs = require('fs')
 app.get('/script.js', (req, res) => {
   res.set({
     'Content-Type': 'application/javascript',
-    'Timing-Allow-Origin': 'http://localhost:8000 http://localhost:8001'
+    'Timing-Allow-Origin': ['http://localhost:8000', 'http://localhost:8001'],
   }).status(200).end('(function () {/* no-op */})()')
 })
```

```bash
> curl -v http://localhost:8002/script.js
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-Type: application/javascript
< Timing-Allow-Origin: http://localhost:8000
< Timing-Allow-Origin: http://localhost:8001
< Date: Tue, 20 Sep 2016 21:16:02 GMT
< Connection: keep-alive
< Content-Length: 29
```

The results are less great than I was hoping for:
- Chrome seems to take the last TAO value - i.e. passes 8001 test and fails 8000.
- Firefox seems to combine both headers with comma and then fails both 8001 and 8000 checks.
- Edge.. not sure, can't test. @nolanlawson @toddreifsteck can you guys try it on your end?

My hope was that we could switch TAO to `origin-or-null / wildcard` and then commas and/or multiple header value to allow for multi-origin whitelists. However, current FF behavior may make that a bit tricky...

**Comment by nolanlawson** [comment]
```
Timing-Allow-Origin: http://localhost:8000
Timing-Allow-Origin: http://localhost:8001
```

* Chrome 53: only 8000 recognized
* Firefox 48: neither recognized
* Edge 14: both recognized

**Comment by igrigorik** [comment]
- Update TAO to `#( origin-or-null / wildcard )` (check on comma syntax stuff)
- We might want to update 4.2.4 HTTP new-header syntax in Fetch to support the same comma separated syntax -- we'll open a separate issue on Fetch. AI: discuss with appsec.

**Comment by nolanlawson** [comment]
FWIW, IE11 matches Edge's behavior, both for the space-separated case and the double-header case.

**Comment by igrigorik** [comment]
Closing, resolved via https://github.com/w3c/resource-timing/pull/68#issuecomment-250791744.
