### ISSUE TITLE
Clarify definition of responseStart

### ISSUE THREAD

**Issue by igrigorik** [w3c/resource-timing#63]
From https://bugs.chromium.org/p/chromium/issues/detail?id=568024: 

http://w3c.github.io/resource-timing/#dom-performanceresourcetiming-responsestart

> Is the first byte the first byte of the first challenge, or the first byte of the actual headers?  What about 100 continue responses?  Do those really count, or do we care about the actual headers for the response? 

I'm inclined to say that the challenge bytes / 100 Continue are valid "responseStart" bytes - i.e. responseStart should capture the time of receipt of 100 Continue / challenge.

@toddreifsteck @annevk how do you guys handle this in your implementations?

> if H2 reads only a partial frame.. 

Is that a valid responseStart marker, or should it reflect receipt of a full frame? Personally I'm leaning towards the latter.

**Comment by annevk** [comment]
We should figure out Fetch integration. This would fall out of that. Not sure about what Fx does.

**Comment by toddreifsteck** [comment]
Edge/IE: For HTTP/2, it is the first full header. For others, it is the first completed receive of bytes. Which could range in size depending on the underlying network.

**Comment by igrigorik** [comment]
@toddreifsteck to clarify, "first full header" would be the first full HEADERS frame.. regardless of whether that frame is carrying `:status:` 100, 200, etc?

**Comment by toddreifsteck** [comment]
Yes, you are correct. The first full HEADERS frame.

**Comment by igrigorik** [comment]
Reviewing the code... 

- From what I can see, Fx sets responseStart as soon as bytes are received: https://github.com/mozilla/gecko-dev/blob/553a2da922bb1d1134ede1f31e609e0d5f6f6a5e/netwerk/protocol/http/nsHttpTransaction.cpp#L758. @mcmanus what happens for the H2 case?
- Chrome's current behavior is to report time when we finished receiving header bytes on the client: https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/timing/PerformanceTiming.cpp?sq=package:chromium&dr=C&l=232-244 - note the FIXME.

@annevk re, fetch integration: it looks like we'd want to extend [5.6 step 4](https://fetch.spec.whatwg.org/#http-network-fetch) to provide a hook for when first header bytes are received?

**Comment by annevk** [comment]
Yeah, seems like it. Does this get reset when there's a redirect then or HTTP authentication?

Perhaps the whole resource timing model should be part of fetch groups and Fetch should be responsible for recording all the values. Resource timing then simply provides the API on top.

**Comment by igrigorik** [comment]
> Does this get reset when there's a redirect then or HTTP authentication?

Yes, it's the first header bytes of the last redirect, assuming said redirect passes timing-allow-check algorithm. Re, HTTP Auth: yes this is valid, same for 100-Continue's -- as in, we should timestamp responseStart when we receive those. 

> Perhaps the whole resource timing model should be part of fetch groups and Fetch should be responsible for recording all the values. Resource timing then simply provides the API on top.

Indeed.. :)

**Comment by annevk** [comment]
Do you require all redirects in the chain to opt into TAO just like we do with CORS?

Is integration with Fetch something that someone in your community/team can take on?

**Comment by igrigorik** [comment]
> Do you require all redirects in the chain to opt into TAO just like we do with CORS?

RT L2 only exposes the _last_ fetch in the chain and said request has to pass the TAO check. 

We do have a bug open for exposing the other fetches in the chain https://github.com/w3c/resource-timing/issues/21 (L3), and fetch integration https://github.com/w3c/resource-timing/issues/39 (also L3)... So, yeah, we'll tackle these once we have L2 all squared away.

**Comment by annevk** [comment]
That does not match CORS semantics. All redirects have to opt in. Pretty sure you get subtle leaks otherwise.

**Comment by igrigorik** [comment]
Discussing at TPAC with Yoav/Todd:

"The time immediately after the user agent receives the first byte of the response headers"

1. In H1 the above is simple (current Edge/FF behavior)
1. In H2 there may be implementation gotchas here.. If we want to match the above h1 semantics we would have to timestamp the receipt of the HEADERS frame header and not wait for the full frame to arrive first.

AI: check-in with net teams on whether (2) is feasible.

**Comment by mcmanus** [comment]
are you concerned about the delta between the first byte of the frame
header and the time the first streamed response header pops out? that
doesn't really seem something worth worrying about - if an implementation
is bad enough that there is a gulf there the later timestamp is probably
more useful to finding the bottleneck anyhow - but honestly, these should
be ~same.

**Comment by igrigorik** [comment]
Patrick: one could imagine tripping over a lost packet, or a congestion window, while transmitting the headers frame.. which would result in RTT+ of misattributed latency... That, and it would be nice to maintain consistency between h1 and h2 as "moment in time when first header bytes were received by the browser"... If it doesn't impose too much architectural pain.

**Comment by mcmanus** [comment]
seriously, this seems uninteresting to sweat and would indeed be a bit of
a pain to implement..

I still think I would argue that the semantic is really the first byte of
actual decoded header data.. not sure why you would give the sender credit
for something that wasn't goodput - the only use case I can see for that is
gaming measurements.

**Comment by MattMenke** [comment]
There's also the issue of auth challenges - is the first auth challenge the first byte of the response?  I assume not.

I'm also wondering if 100s are really part of the response.  They exist to be sent before the server has received the entire request, and are not part of the Javascript-visible response.  While there's no requestEnd event, if 100s are included, responseStart would potentially occur after a requestEnd event, if one were to exist (I don't think that will ever be the case, conceptually, though, it just seems weird to me)

**Comment by igrigorik** [comment]
> I still think I would argue that the semantic is really the first byte of actual decoded header data..

That's reasonable.. But, how would you define this in h1 world? First complete line? The full set of headers (CRLF CRLF)?

> if 100s are included, responseStart would potentially occur after a requestEnd event, if one were to exist (I don't think that will ever be the case, conceptually, though, it just seems weird to me)

Auth challenges have similar concerns, right? That said.. *shrug*.. I think recording the first byte of decoded header data is fine, regardless of response code.

**Comment by MattMenke** [comment]
Auth challenges, the issue is the challenge is actually the response to the previous request, and then a new request was sent, with the auth header.  requestStart should be when the second request was sent, not the first, I assume?

**Comment by MattMenke** [comment]
Also worth noting that server auth and proxy auth uses nearly identical code.  Not a fan of differentiating them by adding different magic to handle requestStart calculation to each of the two paths (Which use basically the same code, for non-tunneled connections).

**Comment by igrigorik** [comment]
> Auth challenges, the issue is the challenge is actually the response to the previous request, and then a new request was sent, with the auth header. requestStart should be when the second request was sent, not the first, I assume?

Hmm, well, I'm contradicting what I said earlier.. but I guess if we think of it the same way as we do about handling redirects, then yes, what you're describing makes sense. @mcmanus any thoughts on this one? 

/cc @bluesmoon @nicjansma

**Comment by mcmanus** [comment]
second one makes sense to me as that's the one with the 'goodput'.

**Comment by bluesmoon** [comment]
Thanks for asking.  What I would like is for `performance.getEntriesByType("navigation")` to return a list of `PerformanceNavigationTiming` object(s).

In the event of a redirect or a 401 or other response that requires multiple HTTP roundtrips between client and server, there would be multiple entries in this list, one for each request/response pair.  Naturally same-origin restrictions would be in place for redirects, so all entries in the returned list will be from the same origin as the final page.

For each entry, `redirect{Start, End, Count}` should encapsulate the timings of all prior entries (since they are all same-origin).

Why is this useful?

For redirects, it tells us if all redirects took the same amount of time or not.  For 401s or equivalent, there might be a period of time where the user agent is blocked waiting for input from the user.  This should not be encapsulated within an opaque `redirectStart` to `redirectEnd`.

**Comment by bluesmoon** [comment]
Just realized that this is for resource-timing.  I don't think it makes a difference, but I'd wouldn't be as concerned if it weren't implemented this way for RT.

**Comment by igrigorik** [comment]
> second one makes sense to me as that's the one with the 'goodput'.

Just to confirm, you're suggesting:
- HTTP/1: all headers have been received (i.e. CRLF CRLF)
- HTTP/2: all HEADERS frames have been received (i.e. HEADERS w/ 'end headers' flag set)

I'm OK with the above, but do note that this is inconsistent with current Edge+FF implementation of responseStart for HTTP/1. Is this something we're willing to change in Edge+FF? Chrome's current implementation matches the above.

> In the event of a redirect or a 401 or other response that requires multiple HTTP roundtrips between client and server, there would be multiple entries in this list, one for each request/response pair.

Yes, that's https://github.com/w3c/resource-timing/issues/21; we're targeting that for L3. With these (L3) semantics in mind, auth requests and/or any other request flow that results in multiple request/response header pairs being exchanged will result in same number of separate entries in the perf timeline. 

However, for L2, what we currently have is: 

> The time immediately after the user agent receives the first byte of the response (snip) from the server if the last non-redirected fetch of the resource passes the timing allow check algorithm.

So, auth flow + L2, responseStart is the receipt of response bytes of the last response (after the challenge).

**Comment by bluesmoon** [comment]
> So, auth flow + L2, responseStart is the receipt of response bytes of the last response (after the challenge).

@igrigorik this is acceptable

**Comment by igrigorik** [comment]
Based on above, it sounds like we're converging on: 

1. We should define responseStart in terms of goodput. Meaning, not simply receipt of the first response byte, but decoded header data that the browser can act on:
  - For HTTP/1 this would be receipt of all header lines.
  - For HTTP/2 this would be receipt of HEADERS/CONTINUATION w/ 'end headers' flag set.

2. Re: auth challenges / continue, etc. Current definition in L2 ties responseStart to "last non-redirect fetch", which implies that it's the receipt of decoded header data of the _last_ fetch. It sounds like this is consistent with what we want to keep; no changes needed.
  - In L3 we'll expose other fetches in this chain as separate entries in the timeline.

---

As noted before, (1) is consistent with how Chrome currently implements RT2, but differs from Edge/FF both of which report the receipt of first byte. @toddreifsteck @mcmanus @valenting are you comfortable with making this change? If so, I can put together a PR.

**Comment by toddreifsteck** [comment]
@igrigorik Discussing with my networking team. Need to postpone this one for the next call..

**Comment by toddreifsteck** [comment]
@igrigorik @mcmanus 

Agreed on 2.

For 1, Microsoft Edge believes that the current specified behavior is a better representation of the intent of responseStart. We believe the intent of responseStart is to measure that the server has begun sending a response and to measure the time from something close to "first byte" until the end of the response.

We would not be comfortable with this change. We WOULD be comfortable with something closer to "first byte".

**Comment by igrigorik** [comment]
@toddreifsteck are you able to accurately timestamp (in Edge) arrival of first byte of the HEADERS frame, even if such frame is split across multiple packets, etc? I could see some implementations struggling with that, as that may be abstracted at a lower layer and you'll only get notification when entire frame is available.

@mcmanus any followup thoughts or objections?

I don't have a strong opinion either way, I think both arguments (timestamp of first byte vs. timestamp of goodput bytes) make sense. We just need to pick one.

**Comment by igrigorik** [comment]
Closed via https://github.com/w3c/resource-timing/pull/83.
