### ISSUE TITLE
Resource timing for audio

### ISSUE THREAD

**Issue by apals** [w3c/resource-timing#65]
Hi,
I'm currently loading audio files on a website, and I suspect that they're taking a long time. `getEntriesByType` does not return any entries for the audio. How can I measure the loading time for these resources? 

<a href="https://www.w3.org/TR/2014/CR-resource-timing-20140325/">Here</a> it points me towards resource timing level 2, but I can't find audio resource timing anywhere. Any pointers?

**Comment by igrigorik** [comment]
AFAIK, there is no reason why audio should be excluded. You could be looking at a browser bug..

Do you have a demo page somewhere? Which browsers have you tested?

**Comment by apals** [comment]
I did it wrong :-). I was looking at >150 resources so it was excluded.
