### ISSUE TITLE
Capturing basic auth credentials in URLs

### ISSUE THREAD

**Issue by plehegar** [w3c/resource-timing#7]
From https://lists.w3.org/Archives/Public/public-web-perf/2015Jan/0069.html
[[
For a quick example go to https://httpbin.org/ and try this out in the
console:

```
var xhr = new XMLHttpRequest();
xhr.open('GET', 'https://foo:bar@httpbin.org/basic-auth/foo/bar');
xhr.send();
setTimeout(function () { alert('Your password is: ' +

performance.getEntriesByType('resource').pop().name.split('@')[0].split(':').pop()
)}, 500);
```

Using basic auth may not be a great idea, but people still do,
inadvertently exposing passwords to other javascript on their pages.
]]

**Comment by igrigorik** [comment]
Aside, but relevant: https://github.com/whatwg/fetch/issues/26 ... fetch() is disallowing requests with credentials in the URL.

**Comment by igrigorik** [comment]
I'm inclined to punt on this. As we migrate towards using fetch across the platform, this problem should go away as these requests (with credentials in URL) would be disallowed. 

Thoughts? /cc @annevk @toddreifsteck

**Comment by annevk** [comment]
What is the problem here? That the URL still contains credentials in `performance.getEntriesByType('resource')`? Not sure I agree that is problematic.

**Comment by toddreifsteck** [comment]
From my perspective, it is useful to explicitly disallow credentials from appearing in the URL in Resource Timing entries (and all other PerformanceEntries) as a reminder.

@igrigorik @annevk What is the reasoning for allowing the credentials portion of a Url to flow into Resource Timings?

**Comment by igrigorik** [comment]
@toddreifsteck if we allow the request, we should allow getting timing data for it; from a developers perspective, it's a surprising and unexpected gotcha if we don't. If you happen to include credentials in said URL -- which is a known anti-pattern -- then that's your own fault.

Also, if fetch() is going to disallow such requests in the future, then there are no timing requests to show... I don't think we should complicate matters on our side in this particular case.

**Comment by annevk** [comment]
Indeed, if a URL that includes credentials results in a fetch (rather than an error, depends on the context at the moment, they are not universally banned), anywhere we expose that fetch needs to include them too. There is no good reason that I can see to filter them out here specifically.

I can see a reason for trying to remove URL credentials from the platform altogether. However, if/when that is done, this will automatically no longer reflect them either. So either way it seems it should not affect this technology.

**Comment by toddreifsteck** [comment]
Microsoft Edge and Internet Explorer does not support basic credentials via xhr. I'm ok if the spec does not mention this and let this be resolved by the current plans to eventually deprecate basic credentials.

**Comment by toddreifsteck** [comment]
They also do not support Urls containing basic credentials in any usage as far as I'm aware.

**Comment by igrigorik** [comment]
Closing, since it's a wontfix.

crbug for disallowing requests with basic auth: https://code.google.com/p/chromium/issues/detail?id=504300

**Comment by annevk** [comment]
@toddreifsteck not even for `ftp` URLs? Do you know what the processing model is for the various contexts if they receive URLs that contain them?
