### ISSUE TITLE
Clarify nextHopProtocol value for cached fetch

### ISSUE THREAD

**Issue by igrigorik** [w3c/resource-timing#73]
https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/Hs5-wPpCPZc/7BVwLbfMAAAJ

> One thing that's a bit unclear about this spec is how it would handle cached loads. Would it return the nextHop for the original fetch or would it return a value like "cache". FWIW at FB we're already differentiating cache via transfer_size = 0. -- @bmaurer 

Inspecting FF's (shipped in M45) implementation: they return the value of the original fetch, which is a sensible implementation given that current definition constrains the returned value to ALPN id's. 

That said, from a developer perspective, returning a value like "cache" or "local" seems (more, I think) sensible. Doing so would remove the need for attribute gymnastics around transferSize (see https://github.com/w3c/resource-timing/issues/42#issuecomment-206508028) to figure out if a resource is cached.. Alternatively, we can return an empty string to indicate that there is no "next hop".

@valenting @toddreifsteck any thoughts or opinions on this one?

**Comment by toddreifsteck** [comment]
I generally prefer 'cache' to empty string as I believe it explicitly describes the "hop" that is taken to get the data.

Curious what FF thinks!

**Comment by bmaurer** [comment]
I'd highly support having something like cache here. It'd be great if browsers had some latitude to expose information about the nature of the cache. Eg cache+memory.

**Comment by valenting** [comment]
>  One thing that's a bit unclear about this spec is how it would handle cached loads. Would it return the nextHop for the original fetch or would it return a value like "cache". FWIW at FB we're already differentiating cache via transfer_size = 0.

This wouldn't always work, as transferSize isn't 0 for revalidated resources. In this case, the value of nextHopProtocol might still be useful indicating protocol used to do a conditional request.

> I'd highly support having something like cache here. It'd be great if browsers had some latitude to expose information about the nature of the cache. Eg cache+memory.

cache+memory, cache+disk, cache+net revalidation are things that might be quite useful to expose. But depending on how much information we want to return, it could be better as a separate attribute.

CC @bzbarsky

**Comment by bzbarsky** [comment]
Is there a specific question I'm being asked here?

**Comment by valenting** [comment]
Maybe you have an opinion on what nextHopProtocol ought to return for cached resources.

**Comment by bzbarsky** [comment]
I don't, sorry.

**Comment by bmaurer** [comment]
>This wouldn't always work, as transferSize isn't 0 for revalidated resources. In this case, the value of nextHopProtocol might still be useful indicating protocol used to do a conditional request.

We detect revalidations with transferSize << encodedBodySize.

**Comment by igrigorik** [comment]
@toddreifsteck @valenting the more I think about it, the more I lean towards empty string for any response that never hits the network. For better or worse, the name we picked ("next hop") implies a network hop, of which there is none for a local cache lookup. If we treat "cache" as a hop, then technically "cache" should be the first hop for most every fetch regardless if it hits the network or not (exception: cache bypass requests), which is not what we want. 

>> I'd highly support having something like cache here. It'd be great if browsers had some latitude to expose information about the nature of the cache. Eg cache+memory.
> cache+memory, cache+disk, cache+net revalidation are things that might be quite useful to expose. But depending on how much information we want to return, it could be better as a separate attribute

If we want to expose such data, I think that's better handled as a separate attribute. I propose we punt "expose different types of local caches" into a separate discussion.. Which also requires considering serviceworker caches, etc.

**Comment by bmaurer** [comment]
@igrigorik: Interesting. If we make cache stats a bigger part of the resource timing API this could be more of an issue. I'd be fine with the empty string if we also add clear indicators to the api specifying the cache status. This would also give a good way to specify revalidation

**Comment by igrigorik** [comment]
Resolved via #78, closing.
