### ISSUE TITLE
[Maintenance, reminder] Cycle environment variables that were encrypted with Travis

### ISSUE THREAD

**Issue by tripu** [w3c/resource-timing#77]
[Travis CI](https://travis-ci.org/) sent a message this week alerting of a bug in the way they used to [encrypt environment variables](https://docs.travis-ci.com/user/encryption-keys/). Owners of this repo should have received it.

Depending on the way encryption was done in this repo using the Travis CLI, those values might have leaked.

This is a reminder for maintainers of this repository to make sure they discard old values, and re-encrypt new ones with the latest version of `travis`, now that the bug has been fixed.

Please close this issue if action has already been taken. Feel free to ping me or *sysreq* if you need help.

**Comment by siusin** [comment]
Thanks for the ping @tripu .

Fixed by commit [7261c38](https://github.com/w3c/resource-timing/commit/7261c3840d4dab6c48f20351340f4e7514a8825b).
