### ISSUE TITLE
Resource Timing entries within the context of a service worker for handled requests?

### ISSUE THREAD

**Issue by KenjiBaheux** [w3c/resource-timing#88]
Context: this came up while talking to a third party provider looking into using Foreign Fetch / Foreign Service Worker to enhance their offering. They want to track the latency impact of this approach and were surprised by not being able to capture the worker startup cost via workerStart.

The use case assumes that a SW gets to see Resource Timing entries for the requests that it handles.

Example:
```HTML
<link rel="style" href="https://example.com/this.css">
```
where this.css responds with a foreign service worker header (https://example.com/sw.js scope:/).

With sw.js, the developer expects to obtain information about the "this.css" request (i.e. workerStart, etc.), perhaps at some later point (e.g. subsequent request).

Does this sound like a valid use case?

**Comment by igrigorik** [comment]
This is an interesting one with a few things to unpack...

(1) The processing section in RT2 [references browsing context](https://www.w3.org/TR/resource-timing-2/#processing-model): _"For each resource fetched by the current browsing context, ..."_. We should add worker contexts to that. 

(2) ServiceWorkers are a special case, which we need to spell out much more explicitly. Specifically, if a request matches a SW scope...
  * Should the matching SW see the resource in it's performance timeline? 
  * Should the matching SW see the resource even if it's a passthrough fetch?

If the answer is yes to either or both of the above, should the SW see all the same attributes and values as the renderer that initiated the fetch? For example, `PerformanceResourceTiming` has `initiator`, which reports the element/API that triggered the fetch, should the SW see that? Ditto for `workerStart`.

My hunch is that the answer to all of the above is "yes". Curious to hear other opinions. 

cc @toddreifsteck @wanderview

---

As of today, at least in Chrome, the answer to all of the above is "no". For example, if you load hpbn.co and query the performance timeline from the renderer you'll see:

```
> performance.getEntries()
[PerformanceNavigationTiming, PerformanceResourceTiming, PerformanceResourceTiming, PerformanceResourceTiming, PerformanceResourceTiming, PerformanceResourceTiming, PerformanceResourceTiming, PerformanceResourceTiming, PerformanceResourceTiming]
```

Whereas, if you query the timeline from the matching SW, you'll see.. nothing:

```
> performance.getEntries()
[]
```

That said, if the SW initiates a fetch on its own (e.g. `fetch('/')`), then that RT entry will showup in its timeline. This behavior makes sense if you consider SW as a vanilla worker, but doesn't account for all the magic and power that SW provides..

**Comment by wanderview** [comment]
I would expect the `fetch(evt.request)` in the SW for a "pass through" to show in the service worker timeline.

I think the outer page should be able to see things like:

* service worker intercept decision time
* service worker FetchEvent dispatch  time
* service worker FetchEvent.respondWith() called time
* service worker FetchEvent.respondWith() promise resolution time
* normal network times if FetchEvent.respondWith() was not called and we fell back to network

**Comment by irori** [comment]
Another interesting thing: Navigation preload responses in SW timeline can have negative timestamps, since they may be started before the SW's time origin.

https://crbug.com/712809 https://crrev.com/2847893003
cc @horo-t

**Comment by spanicker** [comment]
My understanding from past conversation with Ilya is that DOMHighRestimestamp should not be negative.
Should we file a separate bug for this?

**Comment by yoavweiss** [comment]
Is this still relevant now that Foreign Fetch is no longer on the table?


> My understanding from past conversation with Ilya is that DOMHighRestimestamp should not be negative.
> Should we file a separate bug for this?

Navigation preload feels like a separate issue.

**Comment by yoavweiss** [comment]
So my understanding of this is that we have several issues here:
* Should Worker context ResourceTiming entries have `workerStart` for ForeignFetch fetches? Since ForeignFetch is no longer a thing, I think the answer is no. Closing this issue.
* Navigation preload can have negative times -  we should open a separate issue
* Service Worker timeline should have ResourceTiming entries for the resource it fetches. We should open a separate issue to clarify what the right behavior should be
