### ISSUE TITLE
How should time for HSTS "redirect" from http to https be represented?

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/resource-timing#9]

**Comment by toddreifsteck** [comment]
Some great questions from EricLaw on IE's recent blog post at: http://blogs.msdn.com/b/ie/archive/2015/02/16/http-strict-transport-security-comes-to-internet-explorer.aspx

**Comment by igrigorik** [comment]
> UAs need to rewrite all insecure UA "http" URI loads to use the "https" secure scheme for those web sites for which secure policy is enabled.

I think this is a no-op for RT/NT, because there is no "redirect" taking place.. Instead, the UA silently rewrites the scheme of any/all requests for the HSTS host to `https`. 

/cc @ericlaw1979

**Comment by toddreifsteck** [comment]
In addition, per 7.2 of https://tools.ietf.org/id/draft-ietf-websec-strict-transport-sec-14.txt, a site MUST not include the a STS header in an unsecure transport so there should be no redirect possible via that route.

Resolving issue.

**Comment by toddreifsteck** [comment]
Eric, please re-open if you have any questions.

@ericlaw1979
