### ISSUE TITLE
Add response status codes for resources in Resource Timing API.

### ISSUE THREAD

**Issue by vaibhavtripathi** [w3c/resource-timing#90]
I believe resource timing API is missing an essential property. It does not tell if a resource failed loading, which is of utmost important to developers using the Resource Timing API. It would be useful if there is a field called "responseCode" or something, which would indicate whether the resource failed successfully or not.

**Comment by yoavweiss** [comment]
I agree this can provide interesting info, and in a way complete https://github.com/w3c/resource-timing/issues/12, which added errored responses, but don't include any indication for that for requests that got an error response.

**Comment by mehulkar** [comment]
Are there any updates on this issue or have there been more discussions here? How would we get some movement?

**Comment by yoavweiss** [comment]
@abinpaul1 - we can close this as "fixed", right?
