### ISSUE TITLE
mark() and measure() return PerformanceEntries

### ISSUE THREAD

**Issue by nolanlawson** [w3c/resource-timing#91]
Backstory:

- https://twitter.com/Runspired/status/811018788820828160
- https://github.com/nolanlawson/marky#api
- https://github.com/w3c/resource-timing/issues/89#issuecomment-269675336

Currently these APIs return void, which is kind of awkward if you actually want to grab the duration when you do a `measure()`. You could use `PerformanceObserver`, but then a library like `marky` would need its API to be asynchronous.

Is there any reason `mark()` and `measure()` can't directly return PerformanceEntries?

**Comment by igrigorik** [comment]
> Is there any reason mark() and measure() can't directly return PerformanceEntries?

I've wondered the same before.. It seems like a useful feature. 

@plehegar do you recall any of the history of when this was first designed, and whether this was considered?

**Comment by toddreifsteck** [comment]
Moved to proper repo. Closing this copy of the issue.
