### ISSUE TITLE
Clarify resourcetimingbufferfull conditions

### ISSUE THREAD

**Issue by JosephPecoraro** [w3c/resource-timing#95]
The spec text for firing the resourcetimingbufferfull event is poor:

> To add a PerformanceResourceTiming entry (new entry) in the performance entry buffer, run the following steps:
> 
> 1. If resource timing buffer current size is less than resource timing buffer size limit, run the following substeps:
>       * Add new entry to the performance entry buffer.
>       * increase resource timing buffer current size by 1.
> 2. Otherwise, if the resource timing buffer full flag is false, run the following substeps:
>       * fire a simple event named resourcetimingbufferfull at the Document, with its bubbles attribute initialized to true, and has no default action.
>       * set the resource timing buffer full flag to true.

There are a few issues here.

1. Because of the "Otherwise" at the start of Step 2, my reading of this says that if the limit is 4 and the current size is 3, adding 1 new entry will not dispatch a full event. Existing implementations (WebKit, Chrome,  Firefox) all dispatch a full event as soon as the buffer size reaches the limit.

2. Firing a simple event at the "Document" appears incorrect. It should dispatch at the `performance` object itself. Further there is no Document in Workers.

---

I propose:

1. Drop the word "Otherwise" from Step 2.

2. Change "at the Document" to "at the Performance object"

**Comment by smaug----** [comment]
And why the resourcetimingbufferfull event bubbles if it is supposed to be fired at Performance object.

**Comment by yoavweiss** [comment]
Suggested change makes sense to me. Let's discuss on the call.
