### ISSUE TITLE
Graphic should indicate fetchStart is a required field, not a parenthesized zeroed field

### ISSUE THREAD

**Issue by JosephPecoraro** [w3c/resource-timing#98]
The [graphic description](http://yoavweiss.github.io/resource-timing/#processing-model) says:

> Attributes in parenthesis indicate that they may not be available if the resource does not pass the timing allow check algorithm.

fetchStart is shown with parenthesis, but it should not be zeroed [according to the timing allow check](http://yoavweiss.github.io/resource-timing/#cross-origin-resources):

> ... these attributes of its PerformanceResourceTiming object must be set to zero: redirectStart, redirectEnd, domainLookupStart, domainLookupEnd, connectStart, connectEnd, requestStart, responseStart, secureConnectionStart, transferSize, encodedBodySize and decodedBodySize.

Likewise the [description of fetchStart](http://yoavweiss.github.io/resource-timing/#dom-performanceresourcetiming-fetchstart) does not mention returning zero:

> On getting, the fetchStart attribute must return as follows:
>
> * The time immediately before the user agent starts to fetch the final resource in the redirection, if there are HTTP redirects or equivalent.
> * The time immediately before the user agent starts to fetch the resource otherwise.

It seems "(fetchStart)" should be "fetchStart" in the graphic.

**Comment by plehegar** [comment]
agreed. pull request to fix that.
