### ISSUE TITLE
Custom ABNF Syntax specification

### ISSUE THREAD

**Issue by JosephPecoraro** [w3c/resource-timing#99]
Introduced in #62 the [spec uses new ABNF syntax](http://yoavweiss.github.io/resource-timing/#timing-allow-origin), while linking to [RFC5234](https://tools.ietf.org/html/rfc5234):

>       Timing-Allow-Origin = 1#( origin-or-null / wildcard )

The `#` syntax is not listed anywhere in the linked RFC5234. It seems to actually be custom w3 extension, described at [https://www.w3.org/Notation.html](https://www.w3.org/Notation.html) but not linked anywhere by any specification that I could find. Please include add some kind of link.

**Comment by JosephPecoraro** [comment]
Apparently [https://tools.ietf.org/html/rfc7230#section-7](https://tools.ietf.org/html/rfc7230#section-7) is the preferred place. See also https://github.com/whatwg/fetch/issues/489#issuecomment-279682383.

**Comment by igrigorik** [comment]
Good catch! Will update.
